logicalclocks/hopsworks

hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java, hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/conda/CondaController.java
Fix processing Conda commands that wasn't setting the status for libraries
https://logicalclocks.atlassian.net/browse/HOPSWORKS-682
Bug fix
=> [HOPSWORKS-682] Status of Anaconda libs was not updated

hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/FilePreviewDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-696
Bug fix
Filter out control codes from JSON response returned from previewFile
No
Example use-case when this bug occurs:
You write Kafka messages to HDFS **.txt file** without any decoding, and the messages include control code 4: "end of transmission", which means that you cannot preview the file. 
Moreover the preview does not fail …
=> [HOPSWORKS-696] filter out control codes from previewfile response

hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-688
Bug fix
Correctly set the truststore in YARN containers to only contain trusted authorities certificates, not private key certificates of clients.
No
A test-scenario is described below which explains the effects of this PR.
Example user for this test: `kafkapython__meb10000`
1. Start a YARN container, either with jupyter service or …
=> [HOPSWORKS-688] Remove private key cert from truststore in YARN containers

hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/CertificateMaterializerAdmin.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/MaterializerStateResponse.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
[HOPSWORKS-674]  Fine-grain locking when materializing keys locally
[HOPSWORKS-674]  Fine-grain locking for remote crypto material operations
https://logicalclocks.atlassian.net/browse/HOPSWORKS-674
Improvement
Lock per MaterialKey instead of global lock when CertificateMaterializer performs operations
No breaking change
=> [HOPSWORKS-674]  Fine-grain locking for CertificateMaterializer operations

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-745
[Feature] Add necessary configuration files for spark jobs and notebooks to use sparkSQL on top of HopsHive
SparkSQL works on Hive
No
Is linked to changes in livy, livy-chef, spark-chef, and hive-chef
=> HOPSWORKS-745 Make spark compatible with hopsHive

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java, hopsworks-ear/test/spec/projects_spec.rb
=> [HOPSWORKS-843] TensorBoard cleans up certificates twice

hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/FeaturegroupJsonDTO.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/FeaturestoreEntityJsonDTO.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/TrainingDatasetJsonDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/app/FeaturestoreJsonDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java, hopsworks-ear/test/spec/helpers/featurestore_helper.rb, hopsworks-web/yo/app/scripts/controllers/createFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewFeaturegroupVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewTrainingDatasetVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createTrainingDatasetCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateTrainingDatasetCtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-853
Feature
Changes the featurestore API to use jobName instead of JobId. This involves changes to the REST API JSON payload and the util-libraries.
Update the util-libraries 
When this PR is merged, these three PRs can be merged as well:
- https://github.com/logicalclocks/hops-examples/pull/28
- …
=> [HOPSWORKS-866] Support JobName in the Feature Store API

hopsworks-api/src/main/java/io/hops/hopsworks/api/app/ApplicationService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-873?filter=-1
API semantic change
When creating new training datasets if there already exists a training dataset with the same name, it will get overwritten instead of throwing an error.
=> [HOPSWORKS-873] Allow overwrite when creating new training datasets

hopsworks-web/yo/app/scripts/services/ModalService.js
- Add missing provider to the selectFileCtrl
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-878?filter=allopenissues
Bugfix
No
=> [HOPSWORKS-878] Bugfix: Moving files in Hopsworks datasets browser does not work

hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java, hopsworks-ear/test/spec/dataset_spec.rb, hopsworks-ear/test/spec/helpers/variables_helper.rb, hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
[HOPSWORKS-887](https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-887)
There is a new settings variable to enable/disable users from downloading files from within datasets. Be default they are allowed. 
https://github.com/logicalclocks/hops-testing/pull/273
=> [HOPSWORKS-887]  Add flag for throwing error when trying to download a file.

hopsworks-web/yo/app/scripts/controllers/createFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewFeaturegroupVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewTrainingDatasetVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createTrainingDatasetCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateTrainingDatasetCtrl.js, hopsworks-web/yo/app/views/createFeaturegroup.html, hopsworks-web/yo/app/views/createNewFeaturegroupVersion.html, hopsworks-web/yo/app/views/createNewTrainingDatasetVersion.html, hopsworks-web/yo/app/views/createTrainingDataset.html, hopsworks-web/yo/app/views/updateFeaturegroup.html, hopsworks-web/yo/app/views/updateTrainingDataset.html
- Add validation checks for hyphens as Hive do not deal with them very well.
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-929
Bug fix
Hyphens are not allowed in featuregroups or training dataset names to avoid errors in Hive.
No
=> [HOPSWORKS-929] Don't allow hyphen in featuregroup names

hopsworks-web/yo/app/scripts/controllers/createFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewFeaturegroupVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createNewTrainingDatasetVersionCtrl.js, hopsworks-web/yo/app/scripts/controllers/createTrainingDatasetCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/updateTrainingDatasetCtrl.js, hopsworks-web/yo/app/scripts/services/FeaturestoreService.js
- Allow to specify "petastorm" as data format in the metadata of training datasets
https://logicalclocks.atlassian.net/browse/HOPSWORKS-852
feature
users can specify petastorm in the metadata of their training datasets
No
=> [HOPSWORKS-852] Add support for petastorm in feature store

hopsworks-IT/src/test/ruby/spec/factories/remote_material_references.rb, hopsworks-IT/src/test/ruby/spec/projects_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
[HOPSWORKS-905]  Remove all project member's certificates from the materializer and add test
https://logicalclocks.atlassian.net/browse/HOPSWORKS-905
Improvement
When we delete a project, delete any reference (local or remote) from the certificate materializer. Individual micro-services should have done this, but do it as a safe-guard.
=> [HOPSWORKS-905]  Force remove remove material when we delete a project

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- Add missing spark environment variable that hops-util and hops-util-py depends on
https://logicalclocks.atlassian.net/browse/HOPSWORKS-715
Fix bug that was introduced with rebase of HOPSWORKS-715. Reintroduce the environment variables added here that was removed in the rebase (https://github.com/SirOibaf/hopsworks/pull/3/files).
Add HOPSWORKS_PROJECT_ID to environment for jobs and jupyter
No
* **Other …
=> [HOPSWORKS-715] Append bugfix

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java, hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- Only data owners should be allowed to delete feature groups/training datasets not created by themself
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-1029?filter=myopenissues
Feature, more fine-grained access control for feature store operations
Only data owners are allowed to update/delete feature groups/training datasets in the feature store that were created by someone else.
No
* …
=> [HOPSWORKS-1029] Revise project roles permissions to feature store

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java, hopsworks-web/yo/app/views/sparkConfig.html
=> [HOPSWORKS-1071] spark.executor.instances should default to spark.dynamicAllocation.minExecutors for Spark Dynamic configurations

hopsworks-admin/src/main/java/io/hops/hopsworks/admin/jupyter/JupyterNotebooksBean.java, hopsworks-admin/src/main/webapp/WEB-INF/beans.xml, hopsworks-api/src/main/java/com/predic8/membrane/servlet/embedded/MembraneServlet.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterManager.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWT.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTManager.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTTokenWriter.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalJupyterJWTTokenWriter.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/PidAndPort.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/TokenGenerator.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1163
This PR refactors the code in a way that allows an alternative implementation of JupyterProcessMgr and add support for running Jupyter on a remote host. It enable the extraction of configurations and secrets to be able to send them to a remote host. It also changes the way JWT tokens are being deleted for Jupyter to avoid a race condition. Additionally, this PR enables Hopsworks to set the token to be used by Jupyter explicitly.
This code changes the way JWT token are being …
=> [HOPSWORKS-1164] Refactor Jupyter code to support non-localhost implementations

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java, hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py, hopsworks-common/src/main/resources/io/hops/jupyter/kernel_template.json
=> [HOPSWORKS-1210] Jupyter now requires the python kernel.json to be under python{2, 3} dir

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/KafkaService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-432
bug fix
Kafka ACLs are cleared after unsharing a topic or deleting a project
no
=> [HOPSWORKS-432] Clean Kafka ACLs when unsharing a topic or deleting a project

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
The archives are configured in the environment to be used
from the local installation. Remove the duplicated configuration
here to avoid uploading them unnecessarily.
=> [HOPSWORKS-453] Do not configure pyspark archives

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
Remove the explicit configuration of hops-util as it is being put
into the classpath by placing it into the Spark jars folder to speed
up application startup times.
=> [HOPSWORKS-1258] Remove configuration for hops-util

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
Add the ApiKeyRequired annotation to all feature store REST calls
to enable calling them with an API key.
=> [HOPSWORKS-1231][APPEND] Add missing ApiKeyRequired

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/settings/FeaturestoreClientSettingsDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featorestore/FeaturestoreConstants.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1264
New feature
Users can now import existing feature datasets on external storage layers, e.g S3, into the Hopsworks feature store
No
=> [HOPSWORKS-1264] [featurestore] import functionality

hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/KafkaService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java, hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java, hopsworks-web/yo/app/scripts/controllers/kafkaCtrl.js, hopsworks-web/yo/app/scripts/services/KafkaService.js, hopsworks-web/yo/app/views/kafka.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1230
Adds support for changing the schema of an existing Kafka topic
In the Kafka tab, next to the schema version appears a button to change the version. A user is presented a pop-up window with a list of available schema versions.
No
=> [HOPSWORKS-1230] Support changing the schema of an existing Kafka topic

.gitignore, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobControllerIface.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featorestore/FeaturestoreConstants.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java, hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1302
Rest endpoint in enterprise version to send json with job configuration to Hopsworks. This PR is to track the common changes required in the community edition.
Community Edition will throw not implemented error when a request is sent to the new endpoint.
=> [HOPSWORKS-1302] Add endpoint for creating jobs to create training datasets

hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/online_featurestore/OnlineFeaturestoreController.java
- NullPointerException when deleting a project without OnlineFeaturestore
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1368
bugfix
fix the nullpointer bug
No
=> [HOPSWORKS-1368][featurestore][bugfix]

hopsworks-IT/src/test/ruby/spec/admin_spec.rb, hopsworks-IT/src/test/ruby/spec/helpers/session_helper.rb, hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/security/CertificateMaterializerAdmin.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/security/CredentialsResource.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/security/X509Resource.java, hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1362
New feature
Endpoint for admin or agent user securely get users' x.509
=> [HOPSWORKS-1362] Add endpoint for platform admins or agents to get users' x.509 credentials. Required by WebHDFS

hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
metaEnabled got changed from boolean to the MetaStatus enum.
- [*] HOPSWORKS JIRA issue has been opened for this PR
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1466
=> [HOPSWORKS-1466] metaEnabled changed from boolean to MetaStatus enum

hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb, hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/settings/FeaturestoreClientSettingsDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/external/ExternalTrainingDatasetController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/hopsfs/HopsfsTrainingDatasetController.java, hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js, hopsworks-web/yo/app/views/newFeaturegroup.html, hopsworks-web/yo/app/views/newTrainingDataset.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1424
These changes prevent the user of using Upper case characters in featurestore entity names. Instead of silently lower casing everything, which lead to problems when a user tries to get an entity with a name containing upper case letters.
Ran the featurestore tests locally, and they passed
=> [HOPSWORKS-1424][featurestore] Handle upper/lower case for feature group names

hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb, hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupFacade.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/settings/FeaturestoreClientSettingsDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/external/ExternalTrainingDatasetController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/hopsfs/HopsfsTrainingDatasetController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/utils/FeaturestoreInputValidation.java, hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java, hopsworks-web/yo/app/scripts/controllers/newFeaturegroupCtrl.js, hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js, hopsworks-web/yo/app/views/newFeaturegroup.html, hopsworks-web/yo/app/views/newTrainingDataset.html
Featurestore Tests were run locally.
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1435
Unifies the validation of name and description lengths in the backend in order to avoid duplicated code in each controller.
Updating the schema of a training dataset from the UI was buggy and led to a situation where features are accumulated in the schema, because we did not remove the old ones correctly and just added the new ones. This gets fixed with this PR.
The update metadata endpoint will not let you update the metadata of a cached …
=> [HOPSWORKS-1435][featurestore] Unify feature store entity max length validation in backend

hopsworks-web/yo/app/views/jobs.html
Issue: the jobs are not clearly distinguishable in the list and even less once their execution are displayed
- add a border to associate job and its execs
- a visual spacing between jobs in the list
⚠️ This update should be tested locally, it should look like the following screenshot
=> [HOPSWORKS-2033] UI update of job list

hopsworks-IT/src/test/ruby/spec/auxiliary/hello_world.py, hopsworks-IT/src/test/ruby/spec/execution_spec.rb, hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb, hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb, hopsworks-IT/src/test/ruby/spec/helpers/session_helper.rb, hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2018
=> [HOPSWORKS-2018] non admin hops users cannot view spark executors logs

hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
=> [HOPSWORKS-2238] Feature Group schema primary key info not set for partition keys 

hopsworks-web/yo/app/views/python.html
=> [HOPSWORKS-2302] Hide python pip search bar as underlying pip search is now deprecated

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java, hopsworks-web/yo/app/scripts/services/FeaturestoreService.js
…ng and stringifing it adds unneeded double quotes
make sure string is UTF-8 encoded - elastic doesn't like it otherwise
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1978
=> [HOPSWORKS-1978][APPEND] schematized tags

hopsworks-web/yo/app/scripts/controllers/conflictCtrl.js, hopsworks-web/yo/app/views/conflictModal.html
=> [HOPSWORKS-2447] Pip conflicts modal not closing when clicking confirm

hopsworks-IT/src/test/ruby/spec/dataset_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2473
=> [HOPSWORKS-2473] dataset read acl list does not get cleared on dataset delete

hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
(cherry picked from commit b2c9801772da9cf3cf41bbb26b15b0cc1be41571)
=> [HOPSWORKS-2510][2.2] Updating validationType on feature group response contains old value

hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleanerController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/python/search/PyPiLibraryElasticIndexer.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/LibraryUpdatesMonitor.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
=> [HOPSWORKS-2522] PyPiLibraryElasticIndexer leaks indices when unable to connect to PyPi

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
…asets (#859)
(cherry picked from commit 02315e29f69b39a298d2b2afdd9d373b01e35187)
=> [HOPSWORKS-2502][2.2] Add JOB audience to delete endpoint for training datasets

hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/AvroSchemaConstructorController.java, hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestAvroSchemaConstructorController.java
(cherry picked from commit f67496db0ad5711daac582574df88fe87eb6f392)
(cherry picked from commit b86a9da7e72defbafe7ddda64447435e84e6c393)
=> [HOPSWORKS-2536] Online FS Avro schema constructor decimals should take precision and scale

hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
=> [HOPSWORKS-2582] Spark driver cores is incorrectly set to number of configured executor cores

hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetInputValidation.java
=> [HOPSWORKS-2614] Training Dataset from Python with default connector fails

hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb, hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb, hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/StatisticsConfigDTO.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java, hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/statistics/StatisticsConfig.java, hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js, hopsworks-web/yo/app/views/featuregroupViewInfo.html, hopsworks-web/yo/app/views/trainingDatasetViewInfo.html
=> [HOPSWORKS-2681] Profiling optimization

hopsworks-web/yo/app/views/dockerJobConfig.html, hopsworks-web/yo/app/views/jupyter/pythonConfig.html, hopsworks-web/yo/app/views/pythonJobConfig.html
[HOPSWORKS-2660] No user feedback when jupyter is not launched due to cpu/memory constraints
JIRA https://logicalclocks.atlassian.net/browse/HOPSWORKS-2660
Improvement
* Improvement: The warning message for memory less than minimum for on Jupyter and python job UI is triggered on page load in addition to field edit.
[HOPSWORKS-2660]: …
=> [HOPSWORKS-2660] No user feedback when jupyter is not launched due to cpu/memory constraints

hopsworks-IT/src/test/ruby/spec/factories/online_fg_2.rb, hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
=> [HOPSWORKS-2899][append] feature group data preview should default to online feature store

hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
=> [HOPSWORKS-2935] jupyter_spec insufficient spark memory test should set python kernel to false

hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb, hopsworks-IT/src/test/ruby/spec/helpers/search_helper.rb, hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/DatasetAccessController.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreBuilder.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreDTO.java, hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreItemBuilder.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/xattr/dto/FeaturestoreXAttrsConstants.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/FeaturestoreDocType.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchController.java
[HOPSWORKS-3184] feature view search
[HOPSWORKS-3184]: https://hopsworks.atlassian.net/browse/HOPSWORKS-3184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HOPSWORKS-3184] feature view search (#988)

hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java, hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/TestFeatureGroupInputValidation.java
* check partition key column types
* added unit test
* use cached-FG in test
* set time travel format hudi
* Update hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java
Co-authored-by: Moritz Meister <8422705+moritzmeister@users.noreply.github.com>
Co-authored-by: Moritz Meister <8422705+moritzmeister@users.noreply.github.com>
(cherry picked from commit 6b1f5ea6c5730a164949e21588dc0d599cf0d5d6)
* **Does this PR introduce a breaking change?** (What changes might users need to …
=> [FSTORE-473] Check partition key column types (#1191)

pom.xml, project-suppression.xml
=> [HWORKS-364] Update flatbuffers dependency in Hive to address CVE-2020-36632

hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/history/Execution.java, hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/maggy/MaggyDriver.java
=> [HWORKS-390] app_id field in execution table is too short

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultBuilder.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportController.java
* Forcing UTC to avoid timezone issue
* Fix timezone issue in validation report controller
* Fix time formatting of json report written to disk
=> [FSTORE-697] handle timezones in validation report timestamp (#1285)

hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/PythonResourcesController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
* Pyhton resources fixes
* Remove empty line
* Take care of the .
* Rename variable
=> [HWORKS-512] Read cgroup parent from database

pom.xml
https://hopsworks.atlassian.net/browse/HWORKS-675
=> [HWORKS-675] Exclude logback dependencies from zookeeper as they break our logging

hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/HostCertsResource.java, hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java, hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestCertificateSigning.java
[HWORKS-887] Issue Strimzi operator CA certificate
* Update hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/KubeCertsResource.java
* [HWORKS-887] Update check based on suggestion
* [HWORKS-887] Fix tests for BasicConstrains
---------
[HWORKS-887]: https://hopsworks.atlassian.net/browse/HWORKS-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [HWORKS-887] Fix revoke Kubernetes certificate API

hopsworks-common/src/main/java/io/hops/hopsworks/common/jwt/OneTimeJWTRotation.java
https://hopsworks.atlassian.net/browse/HWORKS-996
=> [HWORKS-996] Only the Primary Hopsworks instance in the Active region should rotate and delete the signing key

hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
(cherry picked from commit 2191bade16d5b4b10823c06740cbe33a8d182327)
=> [FSTORE-1134] Enable updating embedding (#1673)

hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb, hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/StorageConnectorUtil.java, hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorController.java, hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/storageconnectors/TestStorageConnectorUtil.java, hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/jdbc/FeaturestoreJdbcConnector.java
supporting storing password in jdbc connector as secret (cherry-pick)
=> [FSTORE-1096] store password as secrets for JDBC connector (#1717)
