logicalclocks/hopsworks

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectRestDTO.java
> [HOPSWORKS-2113] get user projects

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/SortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/FeatureGroupCommitController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/FeatureGroupCommitFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/cached/FeatureGroupCommit.java
> [HOPSWORKS-1374] Append: get commit details in correct order (#317)

- hopsworks-persistence/pom.xml
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/util/FormatUtils.java
- pom.xml
> [HOPSWORKS-2125] Bump hops to 3.2.0.1-RC0

- hopsworks-IT/src/test/ruby/spec/auxiliary/create_mnist_model.py
- hopsworks-IT/src/test/ruby/spec/auxiliary/create_mnist_td.py
- hopsworks-IT/src/test/ruby/spec/experiment_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/model_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/model_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentConverter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ModelXAttr.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/dto/ExperimentDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/dto/ExperimentsEndpointDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelConverter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/dto/ModelDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/dto/ModelsEndpointDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/AccessController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1769
> [HOPSWORKS-1769] enable publishing models to other projects

- hopsworks-IT/src/test/ruby/spec/auxiliary/create_synthetic_fg.py
- hopsworks-IT/src/test/ruby/spec/auxiliary/derive_synthetic_fg.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1769
> [HOPSWORKS-1769][APPEND] enable publishing models to other projects

- hopsworks-web/yo/app/scripts/controllers/profileCtrl.js
- hopsworks-web/yo/app/views/apiKeyModal.html
- hopsworks-web/yo/app/views/userSettings.html
> [HOPSWORKS-2128] fix api key sort (#327)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/OfflineFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/TestFeatureGroupController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2092
> [HOPSWORKS-2092] Overwriting a feature group by dropping/recreating loses default value of appended features

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VersionsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-2083] be off dr-elephant (#323)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
> [HOPSWORKS-2145] Sklearn pid file race condition

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-2129] Should run conda clean after installing a package

- hopsworks-IT/src/test/ruby/spec/auxiliary/create_synthetic_model.py
- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
- hopsworks-IT/src/test/ruby/spec/model_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/AccessController.java
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/controllers/experimentCtrl.js
- hopsworks-web/yo/app/scripts/controllers/modelCtrl.js
- hopsworks-web/yo/app/scripts/services/ProjectMembershipService.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2143
> [HOPSWORKS-2143] experiments/models list for any user with access (including shared)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AllowCORSFilter.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/filter/CORSFilter.java
> Add Access-Control-Expose-Headers to CORS filter headers (#360)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowProxyServlet.java
> [HOPSWORKS-2162] Handle 308 redirection (#359)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitResource.java
Co-authored-by: davitbzh <davit@logicalclocks.com>
> [HOPSWORKS-2164] Add API Key annotation on the commits endpoint  (#362)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/cached/FeatureGroupCommit.java
> Fix Hudi Tests/Tags tests (#363)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
> [HOPSWORKS-2172][HOPSWORKS-1984] (#374)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestOnlineFeatureGroupController.java
> [HOPSWORKS-2172][HOPSWORKS-1984] append - fix tests (#375)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ProjectProvenanceResource.java
> [HOPSWORKS-2176] Add api key annotation to provenance endpoint (#376)

- hopsworks-IT/src/test/ruby/spec/helpers/xattr_helper.rb
- hopsworks-IT/src/test/ruby/spec/xattrs_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2174
> [HOPSWORKS-2174] issues attaching xattr to shared files 

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/history/JobState.java
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/views/jobs.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-2026
> [HOPSWORKS-2026] Add converting notebook job state

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
- hopsworks-web/yo/app/views/newJob.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-288
> [HOPSWORKS-288] Allow editing a jobs configuration property without clearing the rest

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
> [HOPSWORKS-288][append] Remove Python JobType

- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
> [HOPSWORKS-2102][append] Create python job fix

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java
- hopsworks-web/yo/app/scripts/services/DataSetService.js
> [HOPSWORKS-2101] Add resource to download files using api key

- hopsworks-IT/src/test/ruby/spec/auxiliary/environment.yml
- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/PackageSource.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/python/CondaInstallType.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2184] Install Python libraries from Anaconda environment file

- hopsworks-web/yo/app/views/newStorageConnector.html
> [HOPSWORKS-2085] append

- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/views/projectSettings.html
- hopsworks-web/yo/app/views/projectsPanel.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1193
> [HOPSWORKS-1193] Make deleting a project more intuitive

- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
> [HOPSWORKS-288_fix] Fix notebook attachment for HOPSWORKS-288

- README.md
> added Hopsworks IDE plugin in README

- hopsworks-web/yo/app/views/projectSettings.html
> [HOPSWORKS-1193][append] Fix panels to resize in project settings

- hopsworks-IT/src/test/ruby/spec/kafka_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
> [HOPSWORKS-2198] Get schema of shared topic

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/StatisticsController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2219] Remove NaN from statistics (#404)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/FeatureGroupFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Feature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Query.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/Filter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterLogic.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterLogicDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/SqlFilterCondition.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/SqlFilterLogic.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/TestFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
(cherry picked from commit a88ec3f3c063469ed95b516b26cd4ed494bd533d)
> [HOPSWORKS-2134] Extend Query constructor with filter capability

- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2249
> [HOPSWORKS-2249] provenance elasticsearch - count and aggregations should be separate methods

- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvUsageBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsAggregations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsParamBuilder.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2249
> [HOPSWORKS-2249][APPEND] provenance elasticsearch - count and aggregations should be separate methods

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2274
> [HOPSWORKS-2274][APPEND] Feature store "NOT FOUND" errors should return 404

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOps.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsAggregations.java
> [HOPSWORKS-2247] Provenance aggregation for writing apps (#409)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2294] Installing a python library from git should enclose the url in quotes

- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
> [HOPSWORKS-2184] Append, remove nonexisting function

- pom.xml
> [HOPSWORKS-2144] Bumps Hops dependency to 3.2.0.2-RC0

- hopsworks-IT/src/test/ruby/spec/docker_image_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
> [HOPSWORKS-2346] Add cloud format to regex in to identify if project is using python37 base env

- hopsworks-IT/src/test/ruby/spec/docker_image_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/views/project.html
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2324] Display alert if project is using older docker image

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/AbstractFacade.java
> [HOPSWORKS-2293] fix date format

- hopsworks-web/yo/app/views/jupyter/experimentConfig.html
- hopsworks-web/yo/app/views/pythonJobConfig.html
> [HOPSWORKS-2359] Always show GPU configuration fields for Jobs and Jupyter

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/experimentCtrl.js
- hopsworks-web/yo/app/views/datasets.html
- hopsworks-web/yo/app/views/datasetsBrowser.html
- hopsworks-web/yo/app/views/experiments.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2052
> [HOPSWORKS-2052] Save preferences for jobs/page filter

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> Add aks kube type

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/PyPiLibraryElasticIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2303] Change python pip search to use pypi simple index and JSON API

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
> [HOPSWORKS-2398] fix ruby sort

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/featurestore_statistics_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_statistics_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/FilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/statistics/StatisticsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/statistics/StatisticsDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/statistics/StatisticsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/FeatureGroupCommitController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/FeatureGroupCommitFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/FeaturestoreStatisticFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/StatisticsController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/cached/TestFeatureGroupCommitController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/cached/FeatureGroupCommit.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/statistics/FeaturestoreStatistic.java
- hopsworks-web/yo/app/scripts/controllers/fsStatisticsCtrl.js
Use Hudi commit ID as statistics timestamp
> [HOPSWORKS-2139] Use Hudi commit ID as statistics timestamp (#453)

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/python/CondaOp.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2336] It should not be mandatory to provide a version when installing a pip or conda library

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb
- hopsworks-IT/src/test/ruby/spec/snowflake_storage_connector_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/snowflake/FeaturestoreSnowflakeConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/snowflake/FeaturestoreSnowflakeConnectorDTO.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnector.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnectorType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/snowflake/FeaturestoreSnowflakeConnector.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-web/yo/app/views/featurestore.html
> [HOPSWORKS-2314] snowflake connector

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
Co-authored-by: Love Walden <>
> [HOPSWORKS-CLOUD-1524] Add AKS as kube type (#819)

- hopsworks-IT/src/test/ruby/Gemfile
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_attach_xattr_ipython_kernel.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_attach_xattr_pyspark_kernel.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_attach_xattr_spark_kernel.ipynb
- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/spark/SparkJobConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/JupyterSettings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/notebookAttachedJupyterConfigCtrl.js
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/scripts/services/MetadataRestService.js
- hopsworks-web/yo/app/scripts/services/ModalService.js
- hopsworks-web/yo/app/views/datasetsBrowser.html
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
- hopsworks-web/yo/app/views/notebookAttachedJupyterConfigInfo.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-2195
> [HOPSWORKS-2195] Attach Jupyter configuration to notebook as Xattr

- pom.xml
> [HOPSWORKS-2040] Bump hops to 3.2.0.3-SNAPSHOT

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClientController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/app/ProvAppController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleanerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ElasticCache.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/state/ProvStateController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/PyPiLibraryElasticIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-testing/src/main/java/io/hops/hopsworks/testing/provenance/TestProvenanceService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2415
> [HOPSWORKS-2415] reset elastic client in case it uses the wrong certificate

- hopsworks-IT/src/test/ruby/spec/kafka_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaClusterInfoBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaClusterInfoDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2345
> [HOPSWORKS-2345] Get Kafka Broker Endpoints through REST Api

- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/views/jupyter/gitBackendAdvancedConfig.html
> [HOPSWORKS-2368] Do not require API token for working with public GitHub and Gitlab repos using Jupyter

- hopsworks-IT/src/test/ruby/spec/featurestore_validation_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/expectations/fg/FeatureGroupExpectationsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/expectations/fs/FeatureStoreExpectationsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/rules/RulesBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/validations/FeatureGroupValidationsBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/validations/FeatureGroupValidationsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeatureGroupBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FilterBy.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidation/FeatureGroupValidationsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidation/RuleDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ValidationResult.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/Featuregroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/AcceptedType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/FeatureGroupExpectation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/FeatureStoreExpectation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/Rule.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/ValidationRule.java
1. Change validation result feature to a list of features as some rules work on pairs of features2
2. Rename RuleDefinition value_type ot accepted_type
3. Add REST API to filter_by FGs by expectations attached
> [HOPSWORKS-2071][append] Filter FGs by expectations attached

- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/services/XAttrService.js
- [] HOPSWORKS JIRA issue has been opened for this PR
- [] All commits have been squashed down to a single commit
> [HOPSWORKS-2404][APPEND] metadata designer remove - jupyter attach config - fix

- hopsworks-web/yo/app/views/datasetsBrowser.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2195
> [HOPSWORKS-2195][APPEND] Attach Jupyter configuration to notebook as Xattr

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-2445] List python libraries as the last step of project creation

- hopsworks-web/yo/app/views/newStorageConnector.html
> [HOPSWORKS-2395] fix tooltip

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
> [HOPSWORKS-2185][Append] Remove unnecessary import

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/kafka_acl_spec.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/apiKey/ApiKeyResource.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/schemas/SubjectDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/TrainingDatasetFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/AvroSchemaConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/SchemasController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/SubjectsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/AccessController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestAvroSchemaConstructorController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/views/members.html
(cherry picked from commit e23d7784eb5bc5e1529fc95fa1a51cd4459c60a1)
> [HOPSWORKS-2458] Online-FS Service Integration

- pom.xml
> [HOPSWORKS-2476] Bump hops to 3.2.0.3-RC0

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NullJupyterNbVCSController.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-2414] Verify that API token used when starting Jupyter with AutoPushOnShutdown enabled has write access to git repo

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/python/CondaCommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/search/PyPiLibraryElasticIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/LibraryUpdatesMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HopsLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HsfsLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/LatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2326] Display alert if a more recent version of hops or hsfs exists in python service

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/TrainingDatasetFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
>  [HOPSWORKS-2458][Append] Revert TrainingDatasetFeatureDTO

- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/ExecutionFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/history/Execution.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
- hopsworks-web/yo/app/views/dockerJobConfig.html
- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/newJob.html
> [HOPSWORKS-2474] Docker job

- hopsworks-IT/src/test/ruby/spec/admin_users_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/admin_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
> [HOPSWORKS-2460] reset password and delete user

- hopsworks-IT/src/test/ruby/spec/helpers/variables_helper.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/scripts/services/VariablesService.js
- hopsworks-web/yo/app/views/serving.html
> [HOPSWORKS-2481] Add KFServing system variable

- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
> [HOPSWORKS-2195][APPEND] Attach Jupyter configuration to notebook as Xattr, fix python job import

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
> [HOPSWORKS-2502] Add JOB audience to delete endpoint for training datasets

- hopsworks-IT/src/test/ruby/spec/sklearn_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tf_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/scripts/controllers/servingViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/services/ModalService.js
- hopsworks-web/yo/app/views/servingViewInfo.html
> [HOPSWORKS-2492] Improve model serving stability and status consistency

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
> [HOPSWORKS-2510] Updating validationType on feature group response contains old value

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/AbstractFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/ExecutionFacade.java
> [HOPSWORKS-2517] Fix executions filter_by submissiontime lt and gt

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClientController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleanerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/search/PyPiLibraryElasticIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2522
> [HOPSWORKS-2513] elastic index get operation supports a limited regex expression

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/secrets/SecretsController.java
- hopsworks-web/yo/app/scripts/controllers/profileCtrl.js
> [HOPSWORKS-2319] Add API to interact with the secret store

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/SecretsBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/secrets/SecretPlaintext.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/secrets/SecretsController.java
> [HOPSWORKS-2538] Secrets API not setting projectId and visibility in certain cases

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-2520] Installing python libraries with no version and from git should use --no-cache docker build option

- pom.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2551
> [HOPSWORKS-2551] Bump hops dependencies to 3.2.0.4-SNAPSHOT

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/PythonLibraryUpdatesMonitor.java
> [HOPSWORKS-2490] Disable Python Library Updates Monitor for snapshot versions

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplateBuilder.java
> [HOPSWORKS-2555] KAFKA_BROKERS not set in Python kernel

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/MonitoringUrlBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/MonitoringUrlDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/LivySessionDTO.java
> [HOPSWORKS-2552] add monitoring urls

- hopsworks-IT/src/test/ruby/spec/default_job_configuration_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/views/dockerJobConfig.html
- hopsworks-web/yo/app/views/newJob.html
> [HOPSWORKS-2559] Docker job input paths

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/memberCtrl.js
- hopsworks-web/yo/app/views/members.html
> [HOPSWORKS-2537] add variable for disabling user search

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
> [HOPSWORKS-1942][Append] Fix GPU support to work with both Jobs and Jupyter

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Feature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Join.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/JoinDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDatasetJoin.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
Prefix for joining to avoid clashing
> [HOPSWORKS-2375] Prefix for joining to avoid clashing (#554)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
> [HOPSWORKS-2594] Attaching Jupyter config when running notebook with Spark or Python kernel with git backend fails

- hopsworks-api/pom.xml
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/Bootstrap.java
- hopsworks-web/pom.xml
> [HOPSWORKS-2601] fix swagger ui

- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingConf.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/dockerJobConfig.html
- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jupyter/pythonConfig.html
- hopsworks-web/yo/app/views/pythonJobConfig.html
- hopsworks-web/yo/app/views/serving.html
- hopsworks-web/yo/app/views/servingViewInfo.html
> [HOPSWORKS-2560] Support Memory, Cores and GPU as a resource for model serving

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2618
Bug fix
> [HOPSWORKS-2618] Fix NPE when force deleting a Project (#583)

- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobType.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/views/dockerJobConfig.html
- hopsworks-web/yo/app/views/newJob.html
> [HOPSWORKS-2615] Docker job logs

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
> [HOPSWORKS-2631] SYNC_BASE_ENV operation should also show error logs in case of failure

- pom.xml
> [HOPSWORKS-2637] Bump hops to 3.2.0.4-RC0

- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tf_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
> [HOPSWORKS-2167] Add inference logger sidecar and schema version 4

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidation/FeatureGroupValidationsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupDTO.java
> [HOPSWORKS-2645] Support feature validation for on-demand FGs in hsfs

- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/serving.html
- hopsworks-web/yo/bower.json
> [HOPSWORKS-2656][HOPSWORKS-2662] Fix serving UI and set angular-material to v1.1.22

- hopsworks-IT/src/test/ruby/spec/helpers/elastic_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClientController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2638
> [HOPSWORKS-2638] elastic clear cached scrolling contexts

- hopsworks-IT/src/test/ruby/spec/admin_hosts_spec.rb
- hopsworks-IT/src/test/ruby/spec/agent_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/agent_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/hosts_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
> [HOPSWORKS-2640] Cannot start Jupyter if Kafka is offline

- pom.xml
> [HOPSWORKS-2650] Bump hops dependencies to 3.2.0.5-SNAPSHOT

- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
> [HOPSWORKS-2683] Anaconda environment should be exported after every operation

- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2656
> [HOPSWORKS-2656][APPEND] serving path validation fix

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
* https://logicalclocks.atlassian.net/browse/HOPSWORKS-2730
Bug fix
> [HOPSWORKS-2730] Release connection after HTTP request has been relayed

- hopsworks-IT/src/test/ruby/spec/auxiliary/export_model_spark.py
- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/model_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/models/ModelsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2727
> [HOPSWORKS-2727] model export issues in python kernel

- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/NotebookBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NotebookDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [Hopsworks 2709] Add endpoint to retrieve the most recent ran Jupyter notebooks

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/SqlFilterCondition.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
> [HOPSWORKS-2712] Add support for IN condition in query filter

- README.md
> Update docs.hopsworks.ai link to new path

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/NotebookBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostInferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostSkLearnInferenceUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostTfInferenceUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/ServingInferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/ServingInferenceUtils.java
- hopsworks-common/src/test/io/hops/hopsworks/common/serving/inference/ServingInferenceUtilsTest.java
> [HOPSWORKS-2724] Encode inference requests as application/json for internal requests

- pom.xml
> [HOPSWORKS-2754] Bump hops to 3.2.0.5-RC0

- hopsworks-common/src/main/java/io/hops/hopsworks/common/alert/AlertController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionUpdateController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/description/JobAlertStatus.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/project/alert/ProjectServiceAlertStatus.java
> [HOPSWORKS-2772] fix job alert on failure

- hopsworks-IT/src/test/java/io/hops/hopsworks/util/helpers/LoginHelper.java
- hopsworks-IT/src/test/ruby/spec/users_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/AuthStatus.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/AuthenticationStatus.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/OTPAuthStatus.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/NullRemoteUserHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/RemoteUserHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/QrCode.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/registrationCtrl.js
> [HOPSWORKS-2774] fixes for 2fa new ui

- hopsworks-IT/src/test/ruby/spec/featurestore_validation_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidation/FeatureGroupValidationsController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/Name.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/Predicate.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/Rule.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/datavalidation/ValidationRule.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2721] Compliance rules improvements

- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/serving.html
> [HOPSWORKS-2797] Add model name and serving state filters to ServingService

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
> [HOPSWORKS-2818] Serialize Date objects correctly in Query Constructor

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/ExecutionFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/AbstractExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/description/Jobs.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/history/Execution.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2777] Improve deletion of large number of executions per job

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/ProjectAdminInfoDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/VariablesRequest.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/cluster/ServicesActionDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTRequestDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JsonWebTokenDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/split/TrainingDatasetSplitDTO.java
> [HOPSWORKS-2809] fix XmlAccessor

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/xattr/dto/FeaturegroupXAttr.java
> [HOPSWORKS-2790][APPEND] on demand fg added to provenance graph

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/TestFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/utils/TestFeatureGroupInputValidation.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2171] Make sure feature schema exists when creating online feature groups

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
> [HOPSWORKS-2805] Regex for validating library name does not allow square brackets

- hopsworks-web/yo/app/scripts/controllers/modelCtrl.js
- hopsworks-web/yo/app/views/models.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2840
> [HOPSWORKS-2840] model pagination fix

- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/inode/InodeBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvUsageBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
> [HOPSWORKS-2592] Dataset href path is malformed

- hopsworks-IT/src/test/ruby/spec/auxiliary/export_model.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_hsml.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_synth_model.py
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/dto/ModelDTO.java
> [HOPSWORKS-2860] Rename Signature to ModelSchema in ModelDTO

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/PreparedStatementBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/Filter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/pit/PitJoinController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/pit/TestPitJoinController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
Fix batch serving vectors sql syntax
> [HOPSWORKS-2839] Fix batch serving vectors sql syntax (#711)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/inode/InodeBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/ModelRegistryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/ModelRegistryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelExpansionBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelExpansions.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelInputExampleResourceRequest.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelSchemaResourceRequest.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelUtils.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/dto/ModelDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-2868] Model schema and input example should be expandable

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
> [HOPSWORKS-2868][APPEND] Incorrect set method used

- project-suppression.xml
> [HOPSWORKS-2882] add suppression for log4j

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Feature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/Filter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterValue.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
> [HOPSWORKS-2819] Allow feature comparison in query filter

- project-suppression.xml
> [HOPSWORKS-2882]-append suppress CWE-502

- hopsworks-IT/src/test/ruby/spec/default_job_configuration_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/default_job_configuration_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/jobconfig/DefaultJobConfigurationResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/jobconfig/DefaultJobConfigurationFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2884] DefaultJobConfiguration update fails for PySpark/Spark JobType

- project-suppression.xml
> suppress log4j cve-2021-45046

- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-2842][APPEND] Set projectName in jupyterCtrl

- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvLinksBeanParams.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvLinksBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClientController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvLinks.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvLinksParamBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/dto/ProvLinksDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [Hopsworks 2829] Expandable links provenance graph

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-2893] SYNC_BASE_ENV should also check for conflicts

- hopsworks-IT/src/test/ruby/spec/auxiliary/test_hsml.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_synth_model.py
> [HOPSWORKS-2894] adjust model_spec tests to check new input_example format

- .github/mkdocs-master.yml
- .github/mkdocs-release.yml
> Add github actions to build dev and release documentation

- mkdocs.yml
> Update mkdocs.yml to fix canonical URLs

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/AbstractExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/YARNExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2863
> [HOPSWORKS-2863] parallel conversion of same notebook - add execution id to make name unique

- pom.xml
> [HOPSWORKS-2913] Bump Hops dependencies to 3.2.0.6

- hopsworks-IT/src/test/ruby/spec/admin_users_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserIds.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2902] fix for the new UI

- hopsworks-common/pom.xml
> [HOPSWORKS-2920] exclude org.slf4j:slf4j-log4j12 from zookeeper

- .gitignore
> [HOPSWORKS-2926] Appending .gitignore file with vscode specific directories

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/Feature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/Filter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterValue.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetControllerTest.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/statistics/StatisticsConfig.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDataset.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDatasetFilter.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDatasetFilterCondition.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- [HOPSWORKS-2855] Save query filter in training dataset (#727)
- Add missing licenses (#763)
[HOPSWORKS-2855]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HOPSWORKS-2855] Save query filter in training dataset

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
> [HOPSWORKS-2855] Fix failed integration test

- hopsworks-IT/src/test/ruby/spec/auxiliary/export_model.ipynb
- hopsworks-IT/src/test/ruby/spec/auxiliary/test_synth_model.py
> [HOPSWORKS-2930] Update schema and model_schema paths in test notebooks

- docs/compute/index.md
- mkdocs.yml
> [HOPSWORKS-2950] Remove user, project and installation section from hopsworks documentation

- index.html
> Add index.html to forward to compute if landing on root page

- dev/index.html
- latest/index.html
> Forward tags to compute

- mkdocs.yml
> [HOPSWORKS-2954] Add Old Documentation header to mkdocs.yml to point to readthedocs

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
> [HOPSWORKS-2963] NullPointerException when listing tags for model

- hopsworks-api/pom.xml
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/HostsFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/host/Hosts.java
> [HOPSWORKS-2844] Add auto-scaling information to the /metrics endpoint

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/PythonLibraryUpdatesMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HopsLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HsmlLatestVersionAnalyzer.java
> [HOPSWORKS-2951] hsml should also be monitored for minor releases

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/erasureCode/ErasureCodeJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalHostJupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/ServingInferenceUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/FlinkConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
> [HOPSWORKS-2980][HOPSWORKS-2828][HOPSWORKS-2633] Remove single model contraint for non-KF serving

- docs/compute/jobs.md
> [HOPSWORKS-2995] Add job configuration documentation

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/conflicts/EnvironmentConflictsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/command/EnvironmentCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/command/LibraryCommandsResource.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/apiKey/ApiScope.java
> [HOPSWORKS-2989] Add Python API key

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2918] register built in transformations by default for every project in backend

- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticDatasetDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticHitDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticInodeDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticProjectDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2991
The Highlights class from elastic doesn't seem to get serialised correctly when part of a DTO, so we serialize it ourselves when adding it to the DTO. The toString method is enough for our purpose.
> [HOPSWORKS-2991] project/dataset search broken - dto serialization

- alerting/pom.xml
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-alert/pom.xml
- hopsworks-alert/src/test/java/TestAlertManagerConfigTimer.java
- hopsworks-api/pom.xml
- hopsworks-api/src/test/java/io/hops/hopsworks/api/featurestore/commit/TestCommitBuilder.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/elastic/TestElasticClientController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/transformationfunction/TestTransformationFunctionController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/transformationFunction/TransformationFunction.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- pom.xml
…r every project in backend (#811)
> [2.5][HOPSWORKS-2918] register built in transformations by default for every project in backend

- alerting/pom.xml
- hopsworks-alert/pom.xml
- hopsworks-alert/src/test/java/TestAlertManagerConfigTimer.java
- hopsworks-api/pom.xml
- hopsworks-api/src/test/java/io/hops/hopsworks/api/featurestore/commit/TestCommitBuilder.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/elastic/TestElasticClientController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/transformationfunction/TestTransformationFunctionController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/transformationFunction/TransformationFunction.java
- pom.xml
…for every project in backend (#812)
> [HOPSWORKS-2918][Append] Register built-in transformations by defaut for every project in backend

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
> [HOPSWORKS-3018] Set executions_per_job_limit variable in tests

- hopsworks-admin/src/main/webapp/WEB-INF/web.xml
- hopsworks-api/src/main/webapp/WEB-INF/web.xml
- hopsworks-ca/src/main/webapp/WEB-INF/web.xml
- hopsworks-cluster/src/main/webapp/WEB-INF/web.xml
- hopsworks-kmon/src/main/webapp/WEB-INF/web.xml
- hopsworks-testing/src/main/webapp/WEB-INF/web.xml
- hopsworks-web/src/main/webapp/WEB-INF/web.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3028
> [HOPSWORKS-3028] Extend glassfish session timeout to 24h

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/external/ExternalTrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/external/ExternalTrainingDatasetFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/external/ExternalTrainingDataset.java
…ets to support Keywords/Tags (#830)
> [HOPSWORKS-3012] Add dummy file in HopsFS for External Training Datasets to support Keywords/Tags

- hopsworks-web/yo/Gruntfile.js
> [HOPSWORKS-3031] fix web build

- hopsworks-common/src/main/java/io/hops/hopsworks/common/alert/AlertController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionUpdateController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/description/JobAlertStatus.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/project/alert/ProjectServiceAlertStatus.java
> [HOPSWORKS-2772]-2.4 fix yarn state for alerts

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/inference/InferenceResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceVerb.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostInferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostSkLearnInferenceUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostTfInferenceUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/ServingInferenceController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
> [HOPSWORKS-3020][HOPSWORKS-3021] Add :test verb for inference and description field to servings

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/search/PyPiLibraryElasticIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/PythonLibraryUpdatesMonitor.java
> [HOPSWORKS-3038] Add lock management in Python search singletons

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
> [HOPSWORKS-3048] Python library installation using APIKey fails to get the user of the request

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileBuilder.java
> [HOPSWORKS-3042] fix accept user

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/PythonLibraryUpdatesMonitor.java
> [HOPSWORKS-3059] Latest version for monitored library should be null if not available

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/PythonLibraryUpdatesMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HopsworksLatestVersionAnalyzer.java
> [HOPSWORKS-3056] Add hopsworks to monitored libraries

- hopsworks-IT/src/test/ruby/spec/gcs_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/EncryptionSecrets.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/FeatureStoreGcsConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/FeatureStoreGcsConnectorDTO.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/TestGcsConnectorController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnector.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/gcs/EncryptionAlgorithm.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/gcs/FeatureStoreGcsConnector.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-2890] Add Google Cloud Storage Connector (#809)

- pom.xml
> [HOPSWORKS-3072] exclude soa-model-core

- hopsworks-IT/src/test/ruby/spec/stream_feature_group_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupDTO.java
> [HOPSWORKS-3069][Append] Always send Time Travel Type Hudi for Stream Feature Group

- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
* Patch labels in patchConfigMap
> [HOPSWORKS-3040] Add labels to istio auth resources

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3077
> [HOPSWORKS-3077] Conversion of Jupyter Notebook should consider Job Type and Serving

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/statistics/StatisticsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/StatisticsController.java
> do not assume a split if splits is empty

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSWORKS-3090
> [HOPSWORKS-3090] CVE-2022-26612 - flink client vulnerability

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSWORKS-3090
> [HOPSWORKS-3090][APPEND] CVE-2022-26612 - flink client vulnerability

- hopsworks-web/yo/bower.json
> [HOPSWORKS-3093] temp fix for file saver

- hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/services/HostServicesController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/WebCommunication.java
> [HOPSWORKS-3104] fix messages

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
* https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-3115
> [HOPSWORKS-3115] Fix hadoop classpath glob extra space

- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitController.java
> [HOPSWORKS-3032] Add committer in pull configuration

- hopsworks-IT/src/test/ruby/spec/bigquery_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/gcs_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/bigquery/FeaturestoreBigqueryConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/bigquery/FeaturestoreBigqueryConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/FeatureStoreGcsConnectorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/storageconnectors/bigquery/TestBigqueryConnectorController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnector.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnectorType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/bigquery/FeatureStoreBigqueryConnector.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-3010] Add BigQuery Connector

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
https://hopsworks.atlassian.net/browse/HOPSWORKS-3124
> [HOPSWORKS-3124] ruby test - always wait for started executions to stop

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingService.java
> Add JOB audience to get serving endpoint

- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
> [HOPSWORKS-3146]  check project membership

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryBuilder.java
> [HOPSWORKS-3062] [FeatureView] Add Tag resource to TrainingDataset resource

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/conflicts/EnvironmentConflictsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/command/EnvironmentCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/command/LibraryCommandsResource.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/apiKey/ApiScope.java
> [HOPSWORKS-3171] Rename PYTHON scope to PYTHON_LIBRARIES

- hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb
- hopsworks-IT/src/test/ruby/spec/redshift_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/settings/FeaturestoreClientSettingsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/redshift/FeaturestoreRedshiftConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/s3/FeaturestoreS3ConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
(cherry picked from commit 2236d650af07628b26e0daaa966cc2f983f6bda5)
> [HOPSWORKS-3109] remove aws_instance_role (#934)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplateBuilder.java
(cherry picked from commit 2a2fbae9a4b707868a6c7df02c05af943f42a99a)
> [HOPSWORKS-3158] add hopsworks_public_host  (#952)

- hopsworks-IT/src/test/ruby/spec/featureview_trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreKeywordResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
> [HOPSWORKS-3061] [FeatuveView] Add Keyword resource to TrainingDataset resource

- pom.xml
> [HOPSWORKS-3174] Bump-up hops version to 3.2.0.7-SNAPSHOT

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidation/expectations/fs/FeatureStoreExpectationsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/greatexpectations/GreatExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteResource.java
> [HOPSWORKS-3118]-append add annotation for datavalidationv2

- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_sklearn_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_tensorflow_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_tensorflow_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/BatchingConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/BatchingConfigurationConverter.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- [ x All commits have been squashed down to a single commit
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-2501)
> [HOPSWORKS-2501] Add request batching support for kserve deployments

- hopsworks-IT/src/test/ruby/spec/helpers/variables_helper.rb
- hopsworks-IT/src/test/ruby/spec/python_resources.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/PrometheusQueryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/DockerCgroupsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/PythonResourcesController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/PrometheusClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-3127)
> [HOPSWORKS-3127] Monitor resource usage for Docker containers

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FsQueryConstructorResource.java
> [HOPSWORKS-3118]-append add service user to FsQueryConstructorResource

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/ExpectationSuiteController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/datavalidationv2/TestExpectationSuiteController.java
> [HOPSWORKS-3193] Creating Feature Group from UI without Expectation Suite fails

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/QuotasEnforcement.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3197
Bug fix
> [HOPSWORKS-3197] Quotas enforcement for the feature store should account for all types of feature groups

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetDTOBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetExpansionBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetExpansions.java
> [HOPSWORKS-3175]-append revert license to LC

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/OpenSearchService.java
> [HOPSWORKS-3118]-append job config and create opensearch jwt

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSWORKS-3206
> [HOPSWORKS-3206] Bump Hops dependencies to 3.2.0.7

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-3208)
> [HOPSWORKS-3207] Add access for feature group and deployment metrics

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/inference/InferenceResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingWrapper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceEndpoint.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferencePort.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostInferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/ServingInferenceController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-3195] Refactor inference endpoints

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingLogs.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-3211] Endpoint for deployment logs and other improvements

- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/PythonResourcesController.java
> [HOPSWORKS-3189] Python resources fix (#976)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/PythonResourcesController.java
>  [HOPSWORKS-3213] Append, get the metrics only from the headnode on a multinode deployment with no kubernetes (#1000)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
> [HOPSWORKS-3217] Add default values for request batching

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreKeywordResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FsQueryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/activities/ActivityResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewInputValidator.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewTagResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/preparestatement/PreparedStatementResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/query/QueryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/PreparedStatementBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/transformation/TransformationResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewController.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3223
> [HOPSWORKS-3223] feature view refactoring (#1003)

- hopsworks-IT/src/test/ruby/spec/featureview_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewInputValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
…source (#956)
* init
* small changes
* additional tests
* revert changes
Co-authored-by: kenneth <kenneth@logicalclocks.com>
(cherry picked from commit c9e77f26cd11794066b88b150e6bd0c4cfea1a8f)
> [HOPSWORKS-3066] [FeatureView] Add integration test for FeatureView

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tags/TagSchemasBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tags/TagSchemasResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tags/SchemaDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tags/TagSchemasController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tags/TagSchemasControllerIface.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3224
> [HOPSWORKS-3224] complex tags - free mode tag schemas

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-3218] Support custom KServe TensorFlow version

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelUtils.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/ServingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/QuotasEnforcement.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-3232] Only models without deployments can be deleted (#1009)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
> [HOPSWORKS-3246] Include new kafka topic in the serving update response

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featureview/FeatureView.java
> [HOPSWORKS-3251] Add feature view count to feature store dto

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/git_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/GitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/FilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/GitRepositoryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/RepositoryBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/SortBy.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitRepositoryFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/git/GitOpExecution.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/git/GitRepository.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-3239)
> [HOPSWORKS-3239] Add sort and filter for git repositories

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
> [HOPSWORKS-3252] Disable Kafka topic deletion for online feature groups

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/AvroSchemaConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
> [HOPSWORKS-3242] Improve handling of different data types in feature groups across online/offline

- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/FeaturegroupType.java
> [HOPSWORKS-3253] Feature Group Type Enum breaks with Stream Feature Group after upgrade

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettingsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/DockerJobConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/JupyterSettings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/config/DockerConfigurationConverter.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/config/DockerResourcesConverter.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/DockerResourcesConfiguration.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
> [HOPSWORKS-3268] Add DockerJobConfiguration class to community version

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/cloud/CloudRoleMappingResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/cloud/RoleMappingServiceStatus.java
> [HOPSWORKS-3269] add endpoint

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/cloud/CloudRoleMappingResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/cloud/RoleMappingServiceStatus.java
> [HOPSWORKS-3269] add check endpoint

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingConf.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingConfResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/DockerResourcesConfiguration.java
> [HOPSWORKS-3262] Make serving resource limits configurable

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetInputValidation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/split/TrainingDatasetSplitDTO.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/split/SplitType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/TrainingDatasetSplit.java
(cherry picked from commit 5eb7f70f5919a8c07cfb8af8a0d100b036ddbd16)
> [HOPSWORKS-3200] time series split (#1011)

- hopsworks-IT/src/test/ruby/spec/featureview_trainingdataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
(cherry picked from commit fe37a22d6a529fa9240ec315a7b72fcd0aa8ed70)
> [HOPSWORKS-3205] check delete training data

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3314
> [HOPSWORKS-3314] Allow API key as authentication method

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3314
> [HOPSWORKS-3314] Allow API key as authentication method (#1161)

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/git_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitCommandConfigurationValidator.java
[* **Please check if the PR meets the following requirements**](https://hopsworks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-3319)
> [HOPSWORKS-3319] GitLab should require username and token on git pull

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/tensorboard/TensorBoardProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkHistoryServerProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTHelper.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/KibanaProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/proxy/CachedBodyServletInputStream.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/proxy/ModifyHeaderHttpServletRequest.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/proxy/MultiReadHttpServletRequest.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/proxy/ProxyServlet.java
> [HOPSWORKS-3234] grafana revers proxy auth

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HopsworksLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HsfsLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/HsmlLatestVersionAnalyzer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/updates/analyzer/LatestVersionAnalyzer.java
> [HOPSWORKS-3346] LatestVersionAnalyzer fails to find the latest version due to change in version formats including RC

- hopsworks-IT/src/test/ruby/spec/featureview_trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetInputValidation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/split/TrainingDatasetSplitDTO.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/trainingdatasets/TestTrainingDatasetInputValidation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/SplitName.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/SplitType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/TrainingDatasetSplit.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
* refactor split type
* validate time series splits
* validate event time column
* add tests
* add tests
* remove extra license
(cherry picked from commit 6de7993a72ef73bf1b24ea34aef6928f6266c52d)
> [HOPSWORKS-3340] Validate time series split order (#1065)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreItemBuilder.java
- hopsworks-api/src/test/java/io/hops/hopsworks/api/opensearch/featurestore/TestOpenSearchFeaturestoreItemBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchFeaturestoreHit.java
https://hopsworks.atlassian.net/browse/HOPSWORKS-3347
> [HOPSWORKS-3347] Featurestore search - training dataset documents may have no xattr attached

- pom.xml
> [HOPSWORKS-3353] Upgrade Calcite to v1.32

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
(cherry picked from commit ca9514e80500ecaafe058fa23d53009474ab17e6)
> [HOPSWORKS-3289] Throw error when reading td without query

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/ExpectationSuiteDTO.java
> [FSTORE-315] Upgrading ExpectationSuiteDTO creator for correct GE version

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
(cherry picked from commit ca9514e80500ecaafe058fa23d53009474ab17e6)
> 3.0 minor release 

- pom.xml
- project-suppression.xml
> [HOPSWORKS-3353][APPEND] Use calcite 1.32 release version

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/HostCertsResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKIUtils.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/persistence/PKICertificateFacade.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestCertificateRevocation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/pki/PKICertificate.java
https://hopsworks.atlassian.net/browse/HWORKS-122
Bug fix
> [HWORKS-122] Revoke a host certificate even when an exact x509 name is supplied

- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/AppCertsResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestCertificateRevocation.java
* https://hopsworks.atlassian.net/browse/HWORKS-121
> [HWORKS-121] Skip adding Application certificates to CRL

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalHostJupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplateBuilder.java
> [HWORKS-95] Show resource usage in JupyterLab

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
> [HWORKS-95][APPEND] Import DockerJobConfiguration

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> hops-git_0.2.0

- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/DockerCgroupsMonitor.java
> [HWORKS-136] Docker Cgroup cpu.cfs_quota_us should account for number of cores

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/constants/message/ResponseMessages.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/ua/UserAccountsEmailMessages.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UserStatusValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-114] fix password reset

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/experimentCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/loginCtrl.js
- hopsworks-web/yo/app/scripts/controllers/mainCtrl.js
- hopsworks-web/yo/app/scripts/controllers/oauthCallbackCtrl.js
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
> [HOPSWORKS-3278]-append fix download

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/FsJobManagerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ImportFgJobConf.java
> [HOPSWORKS-3337] cherry pick add Import data to FG

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetInputValidation.java
(cherry picked from commit fc89d028373cb30b061ba46a30a7068a3dc23685)
> [HOPSWORKS-3340][APPEND] Fix NPE  (#1115)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
(cherry picked from commit fd724f813cd87ddb7f456ddd19a8c5ac4d659ce3)
> [FSTORE-346] remove exception (#1110)

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/git_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/BranchCommits.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/CloneCommandConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/CommitCommandConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitCommandExecutionStateUpdateDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitCommitDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/PullCommandConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/PushCommandConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/RepositoryActionCommandConfiguration.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/git/GitCommit.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/browse/HWORKS-118)
> [HWORKS-118] Fix failing git tests

- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/test/io/hops/hopsworks/common/dataset/FolderNameValidatorTest.java
> [HWORKS-156] Deleting projects with certain names may delete hopsworks docker images from the registry

- hopsworks-IT/src/test/ruby/spec/helpers/storage_connector_helper.rb
- hopsworks-IT/src/test/ruby/spec/redshift_storage_connector_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/redshift/FeaturestoreRedshiftConnectorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/storageconnectors/redshift/TestRedshiftConnectorController.java
(cherry picked from commit 8e4d64456edcde129bd5aee71959fcda7b1a06fb)
> [FSTORE-325] make database driver optional (#1104)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreEntityDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/FeatureGroupFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupDTO.java
> [FSTORE-370][FSTORE-371] Fix unknown properties in featuregroup feature and NPE in cache featuregroup

- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
> [HWORKS-161] Add final status to Python Jobs

- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/transformationFunction/TransformationFunctionController.java
* correct IN statement for batch serving
* tf output types
* tf output types
* tf output types
* tf output types
* fixed tests
* fixed test
Co-authored-by: Davit Bzhalava <davitbzhalava@MacBook-Pro-som-tillhor-Davit.local>
Co-authored-by: davitbzh <davit.bzhalava@gmail.com>
(cherry picked from commit 02385281e9767225c87dbcc304412549cc1347da)
> [FSTORE-359] Rename Transformation Function Output Types (#1128)

- hopsworks-IT/src/test/ruby/spec/haas_user_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/admin_helper.rb
> [HWORKS-162] remove service user

- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
> [HWORKS-160] airflow fix

- pom.xml
> HWORKS-192: Using hops hadoop master

- hopsworks-IT/src/test/ruby/spec/featureview_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
(cherry picked from commit 46af8af062c24b6ad65d74948bba9c02efd634c7)
> [FSTORE-381] Filter label by feature group (#1137)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
(cherry picked from commit 962f181bb3bb86d86d964bba4f7f7585a605a55b)
> [FSTORE-376] Remove empty feature group from joins #1129

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/GitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/execution/GitExecutionResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/GitRepositoryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/RepositoryBeanParam.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitRepositoryFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitCommandConfigurationValidator.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/browse/HWORKS-34)
> [HWORKS-34] Make git repositories private

- hopsworks-IT/src/test/ruby/spec/bigquery_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/feature_store_activity_spec.rb
- hopsworks-IT/src/test/ruby/spec/featurestore_validation_spec.rb
- hopsworks-IT/src/test/ruby/spec/gcs_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/activities/ActivityBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/activities/ActivityDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/activities/ExpansionBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/expectations/ExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/activity/FeaturestoreActivityFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/expectations/ExpectationController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/suites/ExpectationSuiteController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/suites/ExpectationSuiteDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/StorageConnectorUtil.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/activity/ActivityType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/activity/FeaturestoreActivity.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/activity/FeaturestoreActivityMeta.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- [FSTORE-387] Added feature_store_id and feature_group_id to expectation_suite_dto (#1149)
- [FSTORE-350] Clean up Key Files for Storage Connectors on Delete (#1124)
- [HWORKS-205] fix rest code compilation (#1154)
- [HOPSWORKS-3180][FSTORE-339] data validation activity (#1143)
[FSTORE-387]: https://hopsworks.atlassian.net/browse/FSTORE-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> [FSTORE-387][FSTORE-350][HWORKS-205][FSTORE-339]

- hopsworks-IT/src/test/ruby/spec/feature_store_activity_spec.rb
> [FSTORE-402] Add sleep 1sec to ensure correct timestamp ordering (#1160)

- hopsworks-IT/src/test/ruby/spec/featureview_query_spec.rb
- hopsworks-IT/src/test/ruby/spec/featureview_transformation_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/stream_feature_group_spec.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/FsJobManagerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/JobEntityType.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
> [FSTORE-352][FSTORE-400] Fix IT and fix job config

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectDTO.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/project/CreationStatus.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/project/Project.java
> [HWORKS-202] add project creation status

- hopsworks-IT/src/test/ruby/spec/experiment_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/dto/results/ExperimentResultsDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/results/ExperimentResultsBuilder.java
> [HWORKS-212] remove @XmlAnyAttribute

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitController.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/browse/HWORKS-223)
> [HWORKS-223] Remove username prefix from cloned git repository folder name

- hopsworks-IT/src/test/ruby/spec/redshift_storage_connector_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/redshift/FeaturestoreRedshiftConnectorController.java
(cherry picked from commit a2530dab4d7c62c1c757123c5eb1edfeebeb7688)
> [HWORKS-249] blank string validation for default redshift driver (#1174)

- hopsworks-IT/src/test/ruby/spec/serving_default_sklearn_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/QuotasEnforcement.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusCondition.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusConditionEnum.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusEnum.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingWrapper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/monitor/LocalhostServingMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/util/ServingUtils.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/serving/Serving.java
> [HWORKS-125] Improve status of deployments

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/FsJobManagerController.java
(cherry picked from commit 4f4518e78cff7ede1962c8934775aa5c3e76bd7d)
> [FSTORE-463] fix job config path after job folder refactoring

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
* throw exception if fg not exists
* refactor unused parameter
(cherry picked from commit 3322de16a5959e3a870672071e5a84a4c1cd890d)
> [FSTORE-498] Query filter error handling (#1201)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/ConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/join/JoinController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestOnlineFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/join/TestJoinController.java
> [FSTORE-477] Change Online FS ALTER table algorithm

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
> [FSTORE-388] Weird values in Online FS, after using .append_feature

- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/SqlCondition.java
> [FSTORE-309] Add support for like operator in query filter

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/cached/TestCachedFeatureGroupController.java
> [FSTORE-21] Cannot create streaming feature group without primary key

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-290] Add enable_data_science_profile Hopsworks variable (#1198)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-299] Add enable_jupyter_python_kernel_non_k8s flag (#1210)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/featureview_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/JobFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/FsJobManagerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/utils/FeaturestoreUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/AbstractExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/util/KafkaServingHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/description/Jobs.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [FSTORE-35] [FSTORE-373]

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/GitRepositoryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/repository/GitRepositoryDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitCommandExecutionStateUpdateDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitCommandConfigurationValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/git/config/GitCommandConfiguration.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
[* **Post a link to the associated JIRA issue**](https://hopsworks.atlassian.net/browse/HWORKS-289)
> [HWORKS-289] Add read only flag to git repositories

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/utils/FeaturestoreUtils.java
>  [FSTORE-523] Improve user messages for forbidden actions

- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/GitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/execution/GitExecutionResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/conflicts/EnvironmentConflictsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/command/EnvironmentCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/command/LibraryCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersResource.java
> [HWORKS-341] Add missing Audience.JOB annotation for full hopsworks API compatibility

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/FeatureGroupFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/utils/TestFeatureGroupInputValidation.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [FSTORE-443] Do not allow sending feature group feature offline type to be null

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/QueryController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/TestQueryController.java
(cherry picked from commit 007913830b5bf7ad058355f9fc8b727ee281c4c9)
> [FSTORE-422] Retain right fg event time

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [FSTORE-507] figure out features and their transformation functions when attaching transformation functions with prefixes

- hopsworks-IT/src/test/ruby/spec/adls_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/bigquery_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/featureview_trainingdataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/gcs_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/redshift_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/snowflake_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreConnectorFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/StorageConnectorUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/storageconnectors/TestStorageConnectorUtil.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/FeaturestoreConnector.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [FSTORE-484] Add variables for storage connector types

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/client/HttpClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/client/HttpConnectionManagerBuilder.java
* [HOPSFS-41] Use certificates to access Yarn web UI with 2way auth
* [HOPSFS-41] Reverse default value of isAdmin
* [HOPSFS-41] Disable audit log for methods
https://hopsworks.atlassian.net/browse/HOPSFS-41
[HOPSFS-41]: https://hopsworks.atlassian.net/browse/HOPSFS-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HOPSFS-41]: …
> [HOPSFS-41] Use certificates to access Yarn web UI with 2way auth

- hopsworks-rest-utils/pom.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/filters/CustomJsonProvider.java
> [FSTORE-534] Redshift Connector IAM Role authentication jackson issue with expiration field

- hopsworks-admin/src/main/webapp/security/protected/admin/configure_ldap.xhtml
https://hopsworks.atlassian.net/browse/HWORKS-332
> [HWORKS-332] Allow editing only the mapped Role in LDAP group mapping UI

- hopsworks-IT/src/test/ruby/isolated_tests
- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/haas_user_spec.rb
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetResource.java
- hopsworks-rest-utils/pom.xml
- pom.xml
> [HWORKS-335] fix tests

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSFS-43
> [HOPSFS-43] update hops dependency to 3.2.0.8-RC0

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FsQueryBuilder.java
(cherry picked from commit 352d5ae3b920736dd570de25edaeea8a76d2b5a5)
> [FSTORE-536] Show query label on UI #1247

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetDTO.java
> [HWORKS-339] Ensure the hopsworks tutorials work with 3.1 release

- hopsworks-IT/src/test/ruby/spec/experiment_spec.rb
- hopsworks-IT/src/test/ruby/spec/model_registry_spec.rb
- hopsworks-IT/src/test/ruby/spec/model_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_sklearn_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_sklearn_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_tensorflow_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_default_tensorflow_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/results/ExperimentResultsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/tensorboard/TensorBoardResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/featureFlags/FeatureFlagFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/featureFlags/FeatureFlagRequired.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/featureFlags/FeatureFlags.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/ModelRegistryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/ModelRegistryTagResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/dto/ModelDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/inference/InferenceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HWORKS-290][HWORKS-250] Feature flags filters and hsml 3.0.* compatibility

- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/explicit/ProvExplicitLinksBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/explicit/dto/ProvNodeDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupDTO.java
> [HOPSWORKS-3135][APPEND]&[FSTORE-520]&[FSTORE-520][APPEND]

- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/LongRunningHttpRequests.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-315] limit long running tasks

- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/configuration/CAConf.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/PKIMocking.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestPKI.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://hopsworks.atlassian.net/browse/CLOUD-289
> [CLOUD-289] Do not bootstrap Kubernetes CA if we are using a managed Kubernetes service

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/TrainingDatasetFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetControllerTest.java
(cherry picked from commit cdd7726313d78847c6d47896d93888ce87cc7b3c)
> [FSTORE-558] Attach transformation function to self join query 

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/FsJobManagerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/app/JobEntityType.java
(cherry picked from commit 154e29b877fce58567a389b96149ed04c5c70b71)
> [FSTORE-313] fix compute stats job for external fg (#1209)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvExplicitControllerImpl.java
https://hopsworks.atlassian.net/browse/HWORKS-372
> [HWORKS-372] explicit provenance missing community stereotype

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
> [FSTORE-388][APPEND] Move Agent role to correct endpoint

- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
https://hopsworks.atlassian.net/browse/HWORKS-380
> [HWORKS-380] Close PEMParser resource

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/topics/TopicsBuilder.java
- hopsworks-api/src/test/java/io/hops/hopsworks/api/kafka/topics/TestTopicsBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
> [FSTORE-614] Auto Kafka Topic recreation needs to provide better error message in Hopsworks for APP upgrade

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
> [FSTORE-602] get_or_create_feature_group does not validate feature group name

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkHistoryServerProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
- hopsworks-api/src/main/webapp/WEB-INF/web.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
> [HWORKS-219] use consul for proxy servlet

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/expectations/ExpectationBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/expectations/ExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/greatexpectations/GreatExpectationBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/greatexpectations/GreatExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportFilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportSortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultFilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultSortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/expectations/ExpectationController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/greatexpectations/GreatExpectationFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/results/ValidationResultController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/suites/ExpectationSuiteController.java
> [FSTORE-636] Fix expectation suite update transaction (#1270)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/expectations/ExpectationBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/expectations/ExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/greatexpectations/GreatExpectationBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/greatexpectations/GreatExpectationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportFilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/reports/ValidationReportSortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultFilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/results/ValidationResultSortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/datavalidationv2/suites/ExpectationSuiteResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/expectations/ExpectationController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/greatexpectations/GreatExpectationFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/reports/ValidationReportFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/results/ValidationResultController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/suites/ExpectationSuiteController.java
> [FSTORE-636] sonqrqube fixes 3.1

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
> [FSTORE-691] Train test splits contain NaN column values

- README.md
> [HWORKS-423] Fix slack invite to public hopsworks

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/search/LibrarySearchBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryVersionDTO.java
> [HWORKS-320] Pypi library versions not sorted correctly

- README.md
* Fix slack invite to public hopsworks
* Update readme link as well
> [HWORKS-423] Public slack invite 3.1

- README.md
* Fix slack invite to public hopsworks
* Update readme link as well
> [HWORKS-423] Public slack invite 3.0

- alerting/src/test/java/io/hops/hopsworks/test/config/TestAlertManagerConfigController.java
- hopsworks-alert/src/test/java/TestAlertManagerConfigTimer.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/DatasetResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/proxy/ProxyServlet.java
- hopsworks-api/src/test/java/io/hops/hopsworks/api/opensearch/featurestore/TestOpenSearchFeaturestoreItemBuilder.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestPKIBootstrap.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestPKICRL.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestPKIKeypair.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowDagFacade.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
> [FSTORE-681] Fix blockers in hopsworks noticed by sonarqube

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
> [HWORKS-444] Log aggregation reports incorrect failed status under load

- hopsworks-IT/src/test/ruby/spec/snowflake_storage_connector_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/connectionChecker/ConnectionChecker.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/connectionChecker/ConnectionCheckerDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
(cherry picked from commit 5d4374b9beda2a44594377c650b75afff7f4bc28)
> [FSTORE-628 ] add test connection -snowflake (#1277)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HWORKS-471] Remove usage of docker/dockerfile:experimental

- hopsworks-IT/src/test/ruby/spec/admin_users_spec.rb
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/projects/ProjectsAdminResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/audit/AccountAuditFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/audit/RolesAuditFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/Users.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/audit/AccountAudit.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/audit/RolesAudit.java
> [HWORKS-319] fix force delete project

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HWORKS-484] Consecutive python uninstall commands uses incorrect tag

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/acl/PermissionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/tensorboard/TensorBoardKillTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitTimeoutCommandsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNotebookCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/ZookeeperTopicCleanerTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleaner.java
> [HWORKS-409] cleaner timer bean are too verbose and pollute logs

- pom.xml
> HOPSFS-99: Bumped hadoop version

- hopsworks-common/src/main/java/io/hops/hopsworks/common/pythonresources/PythonResourcesController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
* Pyhton resources fixes
* Remove empty line
* Take care of the .
* Rename variable
> [HWORKS-512] Read cgroup parent from database

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/HostsController.java
> [HWORKS-452]-append fix timers

- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/serving_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/QuotasEnforcement.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusCondition.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusEnum.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
> [HWORKS-483] Add creating status for deployments (#1344) (#1332)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/HostsController.java
> [HWORKS-452]-append revert cloud timer

- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentConverter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelConverter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/opensearch/OpenSearchCache.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/DtoConverter.java
> [HWORKS-447] singleton fix for object mapper and concurrency management

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/Featurestore.java
> [FSTORE-821] Add feature store name to feature store table for REST API

- pom.xml
https://hopsworks.atlassian.net/browse/HWORKS-540
> [HWORKS-540] Bump guava version to 27.0-jre

- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/HDFSContentsRemoteDriver.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/HopsfsMountRemoteDriver.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManagerImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalHostJupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/RemoteFSDriver.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/RemoteFSDriverType.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplateBuilder.java
* Jupyter on Hopsfs-mount
* Materialise certificates before starting server
* Add project name
* Pass base dir instead of project name
* Fuse device
* Request fuse devices
* Refactor and integrtion tests
* Refactor
* Refactor
* Always mount project path when using hopsfs mount
* License headers
* Skip start jupyter from shared dataset test if hopsfs mount is enabled
* Change remote fs driver from boolean to string
* License header
* Apparmor
* PR review comments
* Resolve more comments
* Resolve some more comments
* Fix
* Fix tests
* Fix
* Base dir config
* PR review comments
* Checkout KubeProjectConfigMaps
* **What kind of change does this PR introduce?** (Bug fix, feature, docs …
> [HOPSWORKS-3300] Jupyter on Hopsfs-mount (#1045)

- hopsworks-web/yo/app/scripts/controllers/delaClientCtrl.js
> [HWORKS-558] Old UI getting 404 trying to get dela client

- hopsworks-IT/src/test/ruby/spec/admin_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-ca/pom.xml
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/acl/PermissionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/acl/PermissionsFixer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTTokenWriter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/search/PyPiLibraryOpenSearchIndexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMasterPwdMgm.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/MasterEncryptionPasswordMsgListener.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/MasterPasswordResetResult.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceJWTKeepAlive.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HK2Lookups.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/PayaraClusterManager.java
> [HWORKS-448] fix singletons with concurrency management

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveScratchdirCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNotebookCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceCertificateRotationTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceJWTKeepAlive.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/PayaraClusterManager.java
> [HWORKS-446] fix programmatic timers

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/DockerFileController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/DockerImageController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/DockerRegistryMngr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/DockerRegistryMngrImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://hopsworks.atlassian.net/browse/HWORKS-542
> [HWORKS-542] Docker Library Installer refactor

- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
* Fix failing jupyter tests
* Remove byebug
> [HWORKS-555] Fix failing jupyter tests (#1410)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
https://hopsworks.atlassian.net/browse/HWORKS-542?search_id=1d0504cb-7882-4369-9a59-ba2f333c063a
> [HWORKS-542][APPEND] Docker Library Installer refactor - error msg fix

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HWORKS-448]-append fix for sonar

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
> [HWORKS-521] Append, make sure execution waits for final status

- hopsworks-IT/src/test/ruby/.env.example
> [HWORKS-570] Bump spark version in .env file

- hopsworks-api/src/main/java/io/hops/hopsworks/api/dataset/inode/InodeBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/command/HdfsCommandExecutionFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/command/HdfsCommandExecutionController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/hdfs/command/HdfsCommandExecution.java
> [HWORKS-574] Remove hdfs_inodes FK from hdfs_command_execution

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_validation_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/datavalidationv2/suites/ExpectationSuiteDTO.java
> [HWORKS-586] Upgrade great expectations to 0.14.13

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitCommitsFacade.java
> [HWORKS-608] Git commit message might be bigger than VARCHAR(1000)

- alerting/src/main/java/io/hops/hopsworks/alerting/api/AlertManagerClient.java
- alerting/src/main/java/io/hops/hopsworks/alerting/api/ClientWrapper.java
- alerting/src/main/java/io/hops/hopsworks/alerting/config/AlertManagerConfigController.java
- alerting/src/main/java/io/hops/hopsworks/alerting/config/ConfigUpdater.java
- alerting/src/main/java/io/hops/hopsworks/alerting/config/ConfigValidator.java
- alerting/src/main/java/io/hops/hopsworks/alerting/config/dto/HttpConfig.java
- alerting/src/main/java/io/hops/hopsworks/alerting/config/dto/Responder.java
- alerting/src/test/java/io/hops/hopsworks/test/config/TestAlertManagerConfigController.java
- hopsworks-IT/src/test/ruby/spec/admin_alert_management_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/alert_helper.rb
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/AMClient.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/AMConfigMessageListener.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/AMConfigUpdater.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/AlertManagerConfiguration.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/FixReceiversTimer.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/RestoreAlertManagerConfigTimer.java
- hopsworks-alert/src/main/java/io/hops/hopsworks/alert/util/Constants.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/alert/management/ManagementResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/alert/management/PostableAlertManagerConfig.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/alert/receiver/AdminReceiverResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/alert/route/AdminRouteResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/AlertBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/receiver/ReceiverBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/receiver/ReceiverResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/route/PostableRouteDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/route/RouteBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/alert/route/RouteResource.java
> [HWORKS-609] Alertmanger config missing route.repeat_interval

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/maggy/MaggyCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/acl/PermissionsCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitTimeoutCommandsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/pushgateway/PushgatewayMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jwt/InvalidatedJWTCleanup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jwt/OneTimeJWTRotation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/ZookeeperTopicCleanerTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchCleaner.java
> [HWORKS-599] fix @Schedule timers

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HWORKS-614] hopsworks.login on a project with shared dataset 

- pom.xml
* https://hopsworks.atlassian.net/browse/HWORKS-620
> [HWORKS-620] Bump Hops version in preparation for 3.3.0 release

- hopsworks-IT/src/test/ruby/spec/api_key_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/session_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/apiKey/ApiKeyFilter.java
> [HWORKS-611] block api key access for blocked user

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/python/CondaCommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HWORKS-624] Race condition in LibraryInstaller CondaCommand execution

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/project/TestProjectController.java
https://hopsworks.atlassian.net/browse/HWORKS-628
> [HWORKS-628] Skip project creation failure alert if project exists

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/project/TestProjectController.java
https://hopsworks.atlassian.net/browse/HWORKS-628
> [HWORKS-628] append - skip alerts if project name validation fails

- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/ProjectFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UsersDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/project/TestProjectFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/Users.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
…eate (#1472)
* init
* ruby tests
> [FSTORE-928] Hitting limit of number of projects that one user can create

- hopsworks-service-discovery/pom.xml
> [HWORKS-653] Publish hopsworks-service-discovery module on archiva

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/FlinkConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-670] Set Flink job staging and checkpoint directories per user

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupExpansionBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupExpansions.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
* add expansion to feature groups
* address comment
* address comment # Conflicts:
#	hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
> [FSTORE-964] Add expansion to feature groups 

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/util/DatasetHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/util/DatasetPath.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HWORKS-538] new member added to a pending dataset group

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/jobconfig/DefaultJobConfigurationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/conflicts/EnvironmentConflictsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/command/EnvironmentCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/command/custom/EnvironmentCustomCommandsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/history/EnvironmentHistoryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/command/LibraryCommandsResource.java
> [HWORKS-685] allow HOPS_SERVICE_USER to modify Python environments

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/ServingKeyDTO.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featureview/FeatureViewControllerTest.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featureview/FeatureView.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featureview/ServingKey.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
https://github.com/logicalclocks/hopsworks-ee/pull/1456
https://github.com/logicalclocks/hopsworks-ee/pull/1482
> [FSTORE-921] Resolve serving key in feature view

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/python/CondaCommands.java
> [HWORKS-688] convert error msg to latin1

- hopsworks-IT/src/test/ruby/spec/bigquery_storage_connector_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/bigquery/FeaturestoreBigqueryConnectorController.java
(cherry picked from commit 83384005cfe6943f4fa016283fc67ddf1a5710a0)
> [FSTORE-966] fix update issues-bigquery connector (#1517)

- pom.xml
> RONDB-458: Bump Hop Hadoop Version

- pom.xml
> [HWORKS-727] Bump Hops version to 3.2.0.11-RC0

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/git_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitOpExecutionFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitPaths.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/AsynchronousGitCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitCommandOperationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitContainerArgumentsWriter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/git/config/GitOpExecutionState.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
* Enable cancelling of git execution
* Add more attributes to git log file
* Add index pattern
* Fix add index pattern
* change the sepaator
* PR review comments
* Test async
* Test changes
* Check if already cancelled
* Catch any exception and log it in the cancel execution
* Log with Level INFO
> [HWORKS-522] Enable cancelling of git execution (#1358)

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/stream_feature_group_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/TopicDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/AvroSchemaConstructorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectDTO.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestAvroSchemaConstructorController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/utils/TestFeatureStoreInputValidation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/Featuregroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/kafka/ProjectTopics.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/project/Project.java
> [FSTORE-862] Allow naming of Kafka topics for data ingestion

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkProxyServlet.java
> [HWORKS-681] Flink apis for hopsworks python library

- project-suppression.xml
> [HWORKS-676][HWORKS-677] suppress payara and hive CVEs

- hopsworks-IT/src/test/ruby/spec/helpers/admin_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandLogger.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandStatus.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSOpenSearchController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSReindexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/commands/CommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/commands/search/SearchFSCommandFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/commands/Command.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/commands/search/SearchFSCommandHistory.java
> Missing PRS - HWORKS-547, HWORKS-737

- hopsworks-IT/src/test/ruby/spec/helpers/admin_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandLogger.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandStatus.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSOpenSearchController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSReindexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/commands/CommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/commands/search/SearchFSCommandFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/commands/Command.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/commands/search/SearchFSCommandHistory.java
> Missing PRS on 3.4 - HWORKS-547, HWORKS-737

- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/MaterializedJWTFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/custom/CustomCommandsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/python/CondaCommands.java
> [HWORKS-590] HA testing

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
> [HWORKS-789] Fix git tests (#1584)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/kafka/TestKafkaController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
…re are no kafka topics configured
> [FSTORE-1011] Validation message during data ingestion to FG when there are no kafka topics configured

- hopsworks-IT/src/test/ruby/spec/bigquery_storage_connector_spec.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
* reset connector flag to disable
* remove commented code
(cherry picked from commit 50947d242d477f2d15d2ceea424b5c1b44d57bb0)
> [HWORKS-786] reset connector flag to disable before specs (#1580)

- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/CSRView.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/HostCertsResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKIUtils.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/PKIMocking.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestCreateKeystores.java
- hopsworks-ca/src/test/java/io/hops/hopsworks/ca/controllers/TestPKIUtils.java
* [HWORKS-795] Create Java keystore and send it back as part of signing request response
[HWORKS-795] Test create keystores
* [HWORKS-795] Remove forgotten imports
[HWORKS-795]: https://hopsworks.atlassian.net/browse/HWORKS-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-795]: …
> [HWORKS-795] Create Java keystore and send it back as part of signing request response

- hopsworks-ca/pom.xml
> [HWORKS-795] Add missing dependency in Community Edition

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/acl/PermissionsFixer.java
> [FSTORE-1066] fix permission fixer

- pom.xml
- project-suppression.xml
> [HWORKS-804] upgrade zookeeper

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetControllerTest.java
* handle indexoutofbound error
* reformat
> [FSTORE-1037] ArrayIndexOutOfBounds in TrainingDatasetController

- hopsworks-IT/src/test/ruby/spec/featureview_query_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetControllerTest.java
> [FSTORE-944] Save nested filter in feature view

- hopsworks-common/src/main/java/io/hops/hopsworks/common/alert/AlertController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionUpdateController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
> [HWORKS-553] [HWORKS-865] fix np in yarn monitor

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/commands/CommandsController.java
> [HWORKS-883] Fix Sonarqube issues in CommandsController (#1634)

- pom.xml
HOPSFS-127: Bump Hops Hadoop version to 3.2.0.12 SNAPSHOT
> HOPSFS-127: Bump Hops Hadoop version to 3.2.0.12 SNAPSHOT

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTResource.java
> [HWORKS-743] Add missing auth annotation

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorController.java
> [FSTORE-1126] python mysql client sometimes failed when user name is too long

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/kafka_schema_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
* init
* new resource
* minor fix
* integrations test for getting shared schema
* fix ruby tests
* add test for data owner
* mini fix
* fix feedback
* feedback addressed
* fix getFeaturestoreForProjectWithId
> [FSTORE-1130] Get schema from shared project

- hopsworks-IT/src/test/ruby/spec/gcs_storage_connector_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/gcs/FeatureStoreGcsConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HW-303][FSTORE-989] cherry picking from enterprise

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewInputValidator.java
> [FSTORE-1035][APPEND] Fix NPE when validating FV

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/AsynchronousJobExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/AbstractExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HWORKS-892] Use a single YarnClientWrapper to monitor all jobs

- hopsworks-common/src/main/java/io/hops/hopsworks/common/upload/UploadController.java
> [HWORKS-912] 3.5 append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/upload/UploadController.java
> [HWORKS-912] append 

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
> [HWORKS-958] 3.5 add project null check for FeaturestoreService

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
> [HWORKS-958] add project null check for FeaturestoreService

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeatureGroupPreviewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/PreviewBuilder.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/arrowflight/ArrowFlightConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/arrowflight/ArrowFlightController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/arrowflight/ArrowFlightCredentialDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/arrowflight/ArrowFlightQueryDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/test/io/hops/hopsworks/common/arrowflight/TestArrowFlightController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/TestFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/cached/TestCachedFeatureGroupController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-service-discovery/src/main/java/io/hops/hopsworks/servicediscovery/tags/FlyingDuckTags.java
- pom.xml
>  [FSTORE-1063] Hopsworks data preview should use arrow flight to retrieve data if available

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featureview/FeatureViewResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/Featuregroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featureview/FeatureView.java
> [FSTORE-1147] Online feature store notification system

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
> [HWORKS-958] add null check for FeaturestoreService

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/GrafanaProxyServlet.java
> [HWORKS-896] Allow non admin users to view serving resource usage dashboards

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreFacade.java
> [APPEND][HWORKS-919] Setup online feature store in feature preview and retry

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/similarity_search_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/EmbeddingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/Field.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/OpensearchVectorDatabase.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/VectorDatabase.java
> [FSTORE-1133] Delete embedding index 

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/FilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelExpansions.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelUtils.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/SortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/dto/ModelDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/tags/ModelTagResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/models/ModelFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/models/version/ModelVersionFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/Model.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/version/Metrics.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/version/ModelMetricsConverter.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/version/ModelVersion.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/version/ModelVersionPK.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
> [HWORKS-135] Models backend should store metadata in tables instead of opensearch (#1516)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
> [APPEND][HWORKS-919] Fix setupOnlineFeatureStore

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/tags/ModelTagResource.java
> [HWORKS-135][APPEND] remove faulty imports

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_validation_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreConstants.java
> [FSTORE-927] Upgrade great expectations to 0.15.12 (#1586)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/EmbeddingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ModelDto.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/models/ModelFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/EmbeddingFeature.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/Model.java
* save model to embedding feature
* remove modelId
* address comment
* fix NPE
(cherry picked from commit 6e36379eb4e0e375e01b2874581eac2a2b21ed8d)
> [FSTORE-1190] Attach model to embedding feature

- pom.xml
https://hopsworks.atlassian.net/browse/HWORKS-1023
> [HWORKS-1023] Bump service-discovery-clients dependency

- hopsworks-api/src/main/webapp/WEB-INF/web.xml
- hopsworks-ca/src/main/webapp/WEB-INF/web.xml
- hopsworks-realm/README.md
- hopsworks-realm/pom.xml
- hopsworks-realm/src/main/java/io/hops/hopsworks/realm/jdbc/HopsworksJDBCRealm.java
- hopsworks-realm/src/main/java/io/hops/hopsworks/realm/jdbc/HopsworksLoginModule.java
- hopsworks-testing/src/main/webapp/WEB-INF/web.xml
- hopsworks-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
- project-suppression.xml
- scripts/asadmin
> [HWORKS-860] hopsworks realm

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
(cherry picked from commit 2191bade16d5b4b10823c06740cbe33a8d182327)
> [FSTORE-1134] Enable updating embedding (#1673)

- hopsworks-IT/src/test/ruby/spec/similarity_search_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/EmbeddingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/FeaturegroupPreview.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/EmbeddingFeature.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/OpensearchVectorDatabase.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/VectorDatabase.java
* preview embedding
* check prefix
* modify error message and remove field constructor
* fix style
(cherry picked from commit 4131e862a36b93345c2ddd29933cc4b2a0484625)
> [FSTORE-1135] Preview embedding in vector db in UI (#1698)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
> [HWORKS-1028] New version of nbconvert breaks jupyter notebook preview (#1720)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/HopsKafkaAdminClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaBrokers.java
> [FSTORE-1273] Get Kafka brokers using admin client

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/variables_helper.rb
- hopsworks-IT/src/test/ruby/spec/variables_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-973] share default feature store with new projects

- .github/workflows/hopsworks-tests.yml
- hopsworks-IT/src/test/ruby/spec/haas_user_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-IT/src/test/ruby/spec/users_spec.rb
- pom.xml
- project-suppression.xml
> [HWORKS-1053] [HWORKS-1052] fix tests and cve

- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
> [HWORKS-1082] Always initialize udfso for checking Spark job dependencies (#1738)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/query/filter/FilterController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/query/filter/TestFilterController.java
> [FSTORE-1294] Set Java dateformat  to  24h clock in Filter (#1733)

- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelUtils.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/ModelsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/modelregistry/models/dto/ModelDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/FeatureGroupProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/FeatureViewProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ModelProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/TrainingDatasetProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/explicit/ProvExplicitLinksBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/explicit/dto/ProvArtifactDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ModelLinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ModelLinkFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvArtifact.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvExplicitControllerIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvExplicitLink.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/models/version/ModelVersion.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/provenance/ModelLink.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/provenance/ProvExplicitNode.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
* [HWORKS-938] explicit provenance - model
* fix collector key bug
* fix
* cleanup
* fixes
* fixes
* fix build
* remove unnecessary imports from tests
---------
[HWORKS-938]: https://hopsworks.atlassian.net/browse/HWORKS-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HWORKS-936] Explicit model provenance backend

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/featureview_spec.rb
- hopsworks-IT/src/test/ruby/spec/storage_connector_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/SortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FilterBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/SortBy.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/StorageConnectorBeanParam.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSReindexer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featureview/FeatureViewFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/statistics/StatisticsSortBy.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreConnectorFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/QuotasEnforcement.java
- hopsworks-common/src/test/io/hops/hopsworks/common/security/TestQuotasEnforcement.java
> [FSTORE-1263] Add pagination to backend endpoints for FeatureGroups and StorageConnectors

- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaBrokers.java
- hopsworks-common/src/test/io/hops/hopsworks/common/kafka/TestKafkaBrokers.java
> [HWORKS-1132] Fix kafka in kubernetes

- vector-db/src/main/java/io/hops/hopsworks/vectordb/OpensearchVectorDatabase.java
…in the opensearch schema (#1765)
(cherry picked from commit af7a7dec5a7c084f264c03364e70416b32c815e5)
> [APPEND][FSTORE-1135] Fix preview embedding in the UI when pk is not in the opensearch schema

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/StorageConnectorProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/explicit/ProvExplicitLinksBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/utils/FeaturestoreUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/FeatureGroupLinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/LinkFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvArtifact.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/explicit/ProvExplicitControllerIface.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/Featuregroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/provenance/FeatureGroupLink.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/provenance/ProvExplicitNode.java
> [HWORKS-1104] Explicit storage connector provenance

- hopsworks-IT/src/test/ruby/spec/git_spec.rb
- hopsworks-IT/src/test/ruby/spec/spec_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/code/CodeBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/code/CodeBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/code/CodeResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/git/GitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitPaths.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/git/GitRepositoryRemotesFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/code/CodeController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/AsynchronousGitCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/CommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitJWTManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/GitTimeoutCommandsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/LocalCommandExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/git/util/GitCommandOperationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalNoteBookConverter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NoteBookConverter.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NotebookConversion.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/system/job/SystemJobStatus.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HWORKS-859] run notebook conversion and git commands in kube job for ee

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/connectionChecker/ConnectionChecker.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorDTO.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/jdbc/FeaturestoreJdbcConnector.java
support added for test connection for JDBC connectors. Cherry picking from enterprise.
> [FSTORE-920] support Jdbc test-connection

- hopsworks-ca/pom.xml
- hopsworks-common/pom.xml
- pom.xml
https://hopsworks.atlassian.net/browse/HWORKS-1231
> [HWORKS-1231] Bump BouncyCastle dependency

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/similarity_search_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/EmbeddingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/EmbeddingIndexCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/OpensearchVectorDatabaseConstrainedRetry.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/embedding/VectorDatabaseClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/EmbeddingDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/EmbeddingFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeatureGroupInputValidation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/stream/StreamFeatureGroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/embedding/EmbeddingControllerTest.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/featuregroup/online/TestOnlineFeatureGroupController.java
- hopsworks-common/src/test/io/hops/hopsworks/common/featurestore/utils/TestFeatureGroupInputValidation.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/EmbeddingFeature.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/SimilarityFunctionType.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/SimilarityFunctionTypeConverter.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/OpensearchVectorDatabase.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/VectorDatabase.java
- vector-db/src/main/java/io/hops/hopsworks/vectordb/VectorDatabaseFactory.java
> [FSTORE-1078] Support Similarity Search in the Feature Store v1.5

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
> [FSTORE-1338] Online Feature Group fails to be deleted if the online table was dropped

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandLogger.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/OfflineFeatureGroupController.java
…re group (#1796)
* init
* fix null exception if path doesnt exist
* add test
* fix getSchema
* minor improvement
> [FSTORE-1406] Delete Hive table only if it exists when deleting feature group

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetSharedWithFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/inode/InodeFacade.java
> [HWORKS-1197] Add support for case insensitive search on datasets api

- hopsworks-IT/src/test/ruby/Gemfile
> [HWORKS-1283] Integration tests Gemfile should pin ffi to 1.16.3

- project-suppression.xml
> [HWORKS-1296] Suppress aircompressor 3rd party dependency vulnerability check. Read reasoning in JIRA

- hopsworks-api/src/main/java/io/hops/hopsworks/api/opensearch/featurestore/OpenSearchFeaturestoreItemBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchDoc.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSOpenSearchController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/opensearch/OpenSearchFeaturestoreHit.java
> [HWORKS-1287] add featurestoreId to featurestore search doc

- hopsworks-common/src/main/java/io/hops/hopsworks/common/commands/featurestore/search/SearchFSCommandLogger.java
> [FSTORE-1475] fix partial FG deletion

- pom.xml
HOPSFS-191 Bump Hops Hadoop Version to 3.2.0.15-SNAPSHOT
> HOPSFS-191 Bump Hops Hadoop Version to 3.2.0.15-SNAPSHOT

- pom.xml
HOPSFS-199 Bump Hops Hadoop Version to 3.2.0.15-RC0
> HOPSFS-199 Bump Hops Hadoop Version to 3.2.0.15-RC0
