logicalclocks/hopsworks

- scripts/deploy.sh
> Fix deploy script to not overwrite master release

- hopsworks-web/yo/app/scripts/services/ModalService.js
>  [HOPSWORKS-647] Unshare dataset UI not working - append 

- hopsworks-admin/src/main/webapp/security/protected/admin/projectsManagement.xhtml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-632
https://github.com/logicalclocks/hops-testing/pull/144
> [HOPSWORKS-632] Regex too strict for yarn quota updates in admin ui

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/TfServingService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/serving/TfServing.java
> [HOPSWORKS-643]-amend Fix license for TfServing and TfServingService

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-653] Fix Spark UI links, make size of logs configurable

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AlertView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/CondaCommandView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/ServiceView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/SystemCommandView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certs/CertSigningService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/HeartbeatReplyDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/Hosts.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-ear/test/.env.example
- hopsworks-ear/test/spec/agent_spec.rb
- hopsworks-ear/test/spec/factories/host.rb
- hopsworks-ear/test/spec/helpers/hosts_helper.rb
- hopsworks-ear/test/spec/spec_helper.rb
[HOPSWORKS-596] Add agent heartbeat and register views instead of raw String
[HOPSWORKS-596] Refactor agent API [HOPSWORKS-596] Refactor kagent alerting API
[HOPSWORKS-596] Fix licence
[HOPSWORKS-596]  Fix bug with MessageBodyWriter not found for Hosts entity object
[HOPSWORKS-596]  Add Hopsworks CA path to testing environment example
[HOPSWORKS-596]  Add horovod to ProvidedLibraryNames, resolving conflict with HOPSWORKS-532
[HOPSWORKS-596]  Add environment YML attribute to Conda commands view
[HOPSWORKS-596]  Add builders for conda and system commands views
https://logicalclocks.atlassian.net/browse/HOPSWORKS-596
* **What kind of change does this PR introduce?** (Bug fix, feature, …
> [HOPSWORKS-596] Refactor AgentResource

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/Hosts.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-663
Bug fix
> [HOPSWORKS-663]  Put back methods used in xhtml pages

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/styles/board.css
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-657] Add GPUs to Spark Driver

- hopsworks-ear/test/spec/dataset_spec.rb
- hopsworks-web/yo/app/views/datasetsBrowser.html
> HOPSWORKS-660 Fix unzip/zip permission bug

- hopsworks-api-v2/src/main/java/io/hops/hopsworks/apiV2/projects/ProjectsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HOPSWORKS-668] Project creation ignores failures for Jupyter/Hive

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/service/ProjectServiceEnum.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/TourProjectType.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/projectCreatorCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
> [HOPSWORKS-667] Unify Job logs and Jupyter Elasticsearch index and Kibana objects creation

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-ear/test/.env.example
- hopsworks-ear/test/spec/agent_spec.rb
- hopsworks-ear/test/spec/ca_spec.rb
- hopsworks-ear/test/spec/conda_spec.rb
- hopsworks-ear/test/spec/dataset_spec.rb
- hopsworks-ear/test/spec/ldap_spec.rb
- hopsworks-ear/test/spec/projects_spec.rb
- hopsworks-ear/test/spec/session_spec.rb
- hopsworks-ear/test/spec/tfserving_spec.rb
> [HOPSWORKS-644] Fix tests for multi-vm/tls environment

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kagent/HostServicesFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/conda/CondaController.java
Fine-grain transaction contexts when handling agent heartbeat
https://logicalclocks.atlassian.net/browse/HOPSWORKS-675
Bug fix
> [HOPSWORKS-675]  Fix Tx timing out when handling agent heartbeats

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/SystemCommandView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/HeartbeatReplyDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommand.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommandArguments.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/command/SystemCommandFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/Project.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/ProjectFacade.java
- hopsworks-common/src/main/resources/META-INF/persistence.xml
- hopsworks-ear/test/spec/conda_spec.rb
- hopsworks-ear/test/spec/helpers/conda_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-648
Feature
Kagent will periodically send a list of Anaconda environments to be examined for garbage collection. If so, a system command will be added for the agent in question with the environments that should be deleted
Update with latest kagent and kagent config
Depends on:
* https://github.com/logicalclocks/kagent-chef/pull/58
* …
> [HOPSWORKS-648] Anaconda environments GC

- hopsworks-api-v2/src/main/java/io/hops/hopsworks/apiV2/projects/ProjectsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettingsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/TourProjectType.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
- hopsworks-web/yo/app/scripts/services/TourService.js
- hopsworks-web/yo/app/styles/angular-tour.css
- hopsworks-web/yo/app/views/home.html
- hopsworks-web/yo/app/views/jobMonitor.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-607] Replace TensorFlow tour with Deep Learning tour

- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-607] append - Fix tour creation spinner

- hopsworks-web/yo/app/views/jobMonitor.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-684] Fix TensorBoard broken for single experiment

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsGroupsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsUsersFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterPaths.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMapping.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tensorflow/TfLibMappingUtil.java
- hopsworks-common/src/main/resources/META-INF/persistence.xml
> [HOPSWORKS-604] Review Cuda/CuDnn installation and update

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/services/JupyterService.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-690] Add button to stop particular livy session

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
> [HOPSWORKS-704] TensorBoard in Experiments service not showing events

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDep.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
Anaconda libs status didn't update during installation of environment
https://logicalclocks.atlassian.net/browse/HOPSWORKS-707
Bug fix
This fix https://logicalclocks.atlassian.net/browse/HOPSWORKS-682 did not work
> [HOPSWORKS-707]  Fix conda lib status

- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
> HOPSWORKS-666 mmlspark breaks reproducible environments

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-705] Extend TfLibMapping to support ongoing environment creation

- hopsworks-ear/test/spec/conda_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-582
Depends on https://github.com/logicalclocks/kagent-chef/pull/61
> [HOPSWORKS-582]  Update tests to use FQDN instead of the alias

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-722] Remove horovod

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
> [HOPSWORKS-731] Add additional Distributed Training configuration check to JupyterConfigFilesGenerator

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobScheduler.java
- hopsworks-web/yo/app/scripts/controllers/jobDetailCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jobs.html
> [HOPSWORKS-299] Add functionality for job unschedule

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-758
> [HOPSWORKS-758] Make py4j archive name configurable

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfsUser/HdfsGroupsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-757
Fix code that was trying to create Kibana objects twice during project creation. Other fixes such are removing hard-coded versions.
> HOPSWORKS-757

- hopsworks-ear/test/spec/appservice_spec.rb
- hopsworks-ear/test/spec/conda_spec.rb
- hopsworks-ear/test/spec/helpers/appservice_helper.rb
- hopsworks-ear/test/spec/helpers/kafka_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-768
Bug fix
> [HOPSWORKS-768]  Filter user keystore by username in addition to project name

- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceProperties.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/RestDTO.java
> HOPSWORKS-765

- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/LibVersions.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-767] Support installing multiple library versions with pip

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectsManagementBean.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-ear/test/spec/projects_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-777
Bug fix
> [HOPSWORKS-777] Fix project removal by admins

- hopsworks-api/src/main/java/io/hops/hopsworks/api/kibana/KibanaProxyServlet.java
> [HOPSWORKS-790] KibanaProxyServlet lowercase projectname

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
TensorBoardService lowercase projectname
> HOPSWORKS-790 append

- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-795] Jupyter missing preselected mode

- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfigFactory.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServer.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImpl.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/socket/NotebookServerImplFactory.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/util/ZeppelinProjectCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
Fix deadlock in hopsutils gethadoopglobclasspath
> [HOPSWORKS-784] append

- hopsworks-api/pom.xml
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/CondaCommandView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/ServiceView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/SystemCommandView.java
- hopsworks-api/src/main/webapp/WEB-INF/web.xml
- hopsworks-ca/pom.xml
- hopsworks-ca/src/main/webapp/WEB-INF/web.xml
- hopsworks-cluster/pom.xml
- hopsworks-cluster/src/main/webapp/WEB-INF/web.xml
- hopsworks-ear/test/spec/swagger_spec.rb
[HOPSWORKS-797](https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-797)
Remove swagger dataType as it cannot resolve the enum classes. Add swagger test and replace hardcoded version in web.xml.
> [HOPSWORKS-797] Swagger broken

- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardKillTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/experimentsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-793] TensorBoard too long-lived

- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/TfServingView.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/experiments.html
- hopsworks-web/yo/app/views/serving.html
> [HOPSWORKS-799] Lowercase project name for TfServing logs

- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
> [HOPSWORKS-812] TensorBoard poller running too often

- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/Project.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/FolderNameValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-ear/test/spec/conda_spec.rb
- hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/conda/CondaController.java
- hopsworks-web/yo/app/scripts/controllers/pythonDepsCtrl.js
- [ X] HOPSWORKS JIRA issue has been opened for this PR
- [ X] All commits have been squashed down to a single commit
https://logicalclocks.atlassian.net/browse/HOPSWORKS-811
feature
This PR only creates a conda environment for a project when a new library is installed or a library is removed from a project. Otherwise, the project will use one of the base python36 or python27 environments.
No.
* **Other …
> [HOPSWORKS-811] Lazy Conda Environment Creation

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-ear/test/spec/conda_spec.rb
> [HOPSWORKS-811-append] Lazy conda env creation

- hopsworks-api/src/main/java/io/hops/hopsworks/api/zeppelin/server/ZeppelinConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-810
Improvement
Depends on:
https://github.com/logicalclocks/hopsworks-chef/pull/226
https://github.com/logicalclocks/chef-glassfish/pull/2
> [HOPSWORKS-810]  Read Hadoop classpath from env variable

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/configuration/JobConfigurationConverter.java
> [HOPSWORKS-820] Only one JAXBContext should be created per JobConfiguration

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/ExecutionService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTHelper.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/MetadataService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
- hopsworks-ear/test/spec/dataset_spec.rb
- hopsworks-web/yo/app/scripts/controllers/mainCtrl.js
- hopsworks-web/yo/app/scripts/services/AuthGuardService.js
> [HOPSWORKS-661] append

- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorboardProxyServlet.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-813] speedup TensorBoard in experiments service

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/RequestService.java
> [HOPSWORKS-815] Mail from dataset request addressing the wrong user

- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-801] Jupyter running applications view/kill buttons now showing in low resolutions

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-833
Bug fix
> [HOPSWORKS-833]  Fix NPE

- hopsworks-common/pom.xml
- hopsworks-jwt/pom.xml
- pom.xml
> [HOPSWORKS-787] Deploy Hopsworks artifacts on the Maven repo

- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/CondaCommandView.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterPaths.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/CondaCommands.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/EnvironmentYmlJson.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/pythonDeps/PythonDepsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
- hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaDatasetController.java
- hopsworks-ear/test/spec/helpers/project_helper.rb
- hopsworks-ear/test/spec/jupyter_spec.rb
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/services/PythonDepsService.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/selectEnvYml.html
> [HOPSWORKS-750] Jupyter server should use the project conda env

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/YarnUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobService.java
- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-857
> [HOPSWORKS-857] Fix and refactor job UI

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HOPSWORKS-850] Experiments dashboard should be created when jobs service is added

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardProxyServlet.java
- hopsworks-api/src/main/webapp/WEB-INF/web.xml
- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
> [HOPSWORKS-845] TensorBoardProxyServlet fix IllegalStateException

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
Return execution id when killing jobs. Check jupyter installed after enabling python.
> [HOPSWORKS-510] Append. 

- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
> HOPSWORKS-885

- hopsworks-web/yo/app/navProject.html
> [HOPSWORKS-893] Remove zeppelin service icon

- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AuthFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-890
Improvement
JWT issuer will be a common organization identifier
> [HOPSWORKS-890]  Change JWT issuer to be an organization identifier

- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/InferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/LocalhostTfInferenceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/logger/KafkaInferenceLogger.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-894] InferenceController implementations should use connection pooling

- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
> [HOPSWORKS-899] Fix if clause for tours

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/description/JobFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobs/quota/YarnProjectsQuotaFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/configuration/JobConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-ear/test/spec/execution_spec.rb
- hopsworks-ear/test/spec/helpers/job_helper.rb
- hopsworks-ear/test/spec/job_spec.rb
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/services/JobService.js
- hopsworks-web/yo/app/styles/style.css
- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/newJob.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-872
> [HOPSWORKS-872] Editable job

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-907
Bug fix
> [HOPSWORKS-907]  Fix bug when failed to cancel crypto material removal

- pom.xml
> [HOPSWORKS-918] Bump Hops depdendency in Hopsworks to 2.8.2.7

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-ear/test/spec/activity_spec.rb
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/views/jobs.html
- scripts/scp-deploy-frontend.sh
Improve make a copy, reset jobs js table if number of jobs has change…d. Fix activity tests.
> [HOPSWORKS-872] Append

- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/views/jobs.html
Fix getjobsstatus when there are jobs older than 1 month in project. Add missing GENERATING_CERTS job state in front-end.
> [HOPSWORKS-510] Append 

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-933
Bug fix
> [HOPSWORKS-933]  Fix bug with project services

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
> [HOPSWORKS-938] Adding pyFiles to Jupyter does not add it to python path

- hopsworks-web/yo/app/scripts/controllers/featuregroupViewInfoCtrl.js
- Fix undefined variable to the correct name in the feature store UI
https://logicalclocks.atlassian.net/browse/HOPSWORKS-930
Bugfix
Fix undefined javascript variable to the correct variable name
> [HOPSWORKS-930] - undefined featurestore in frontend

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/OpensslOperations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKI.java
- hopsworks-ear/test/spec/ca_spec.rb
- hopsworks-ear/test/spec/helpers/ca_helper.rb
> [HOPSWORKS-897] Hopsworks-ca should set expiration date not validity in days

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/RequestService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/dataset/DatasetRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/exception/RESTCodes.java
- hopsworks-ear/test/spec/conda_spec.rb
- hopsworks-ear/test/spec/dataset_spec.rb
- hopsworks-ear/test/spec/helpers/factory_helper.rb
- hopsworks-ear/test/spec/helpers/project_helper.rb
- hopsworks-ear/test/spec/projects_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-941
Fix dataset request tests, fix randomid, fix requestaccess.
> [HOPSWORKS-941] Fix tests

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/project/ProjectQuotas.java
- hopsworks-admin/src/main/webapp/security/protected/admin/projectsManagement.xhtml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-913
Bug fix
The variable that decides the feature store quota can be edited from the admin UI
No
> [HOPSWORKS-913] Feature store quota missing from admin UI in hopsworks

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
- hopsworks-web/yo/app/scripts/controllers/createNewTrainingDatasetVersionCtrl.js
- hopsworks-web/yo/app/scripts/controllers/createTrainingDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/updateTrainingDatasetCtrl.js
- Add avro spark dependency
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-912
Feature
New datatypes supported for feature store training datasets (e.g Avro/Image)
> [HOPSWORKS-912] support image and avro types in featurestore

- hopsworks-ear/test/Gemfile
- hopsworks-ear/test/spec/spec_helper.rb
- hopsworks-ear/test/spec/tfserving_spec.rb
> [HOPSWORKS-770] Disable HTTP and TLS 1.0

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowJWTManager.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-958
Bug fix
> [HOPSWORKS-958]  Fix bug with Airflow JWT renewer

- hopsworks-ear/test/.env.example
- hopsworks-ear/test/spec/helpers/ca_helper.rb
> [HOPSWORKS-957] Fix flaky CA test

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/AuthStatus.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/loginCtrl.js
- hopsworks-web/yo/app/scripts/controllers/profileCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/js/util.js
- hopsworks-web/yo/app/scripts/services/AuthService.js
- hopsworks-web/yo/app/scripts/services/CertService.js
- hopsworks-web/yo/app/scripts/services/RequestInterceptorService.js
- hopsworks-web/yo/app/views/login.html
- hopsworks-web/yo/app/views/profile.html
> [HOPSWORKS-944] kerberos changes

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/PKI.java
> [HOPSWORKS-957] Certificate enddate should always be UTC

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/Execution.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/ExecutionFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/AsynchronousJobExecutor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/erasureCode/ErasureCodeJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/HopsJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-ear/test/.env.example
- hopsworks-ear/test/spec/execution_spec.rb
- hopsworks-ear/test/spec/job_spec.rb
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-920
https://github.com/logicalclocks/hops-testing/pull/305
> [HOPSWORKS-920] Kill jobs properly

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/WebCommunication.java
- hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/communication/CommunicationController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-953
Bug fix
> [HOPSWORKS-953]  Read response entity instead of error phrase

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/views/datasetsBrowser.html
- hopsworks-web/yo/app/views/project.html
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-968
Bug fix
> [HOPSWORKS-968] fix dataset browser

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/resources/io/hops/jupyter/kernel_template.json
> [HOPSWORKS-969] Install PyHopsHive in the base environment

- hopsworks-ear/test/spec/conda_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-974
Bug fix
> [HOPSWORKS-974]  Fix bug with date format in rspec

- hopsworks-web/yo/app/scripts/controllers/filemgr/main.js
- hopsworks-web/yo/app/scripts/controllers/filemgr/selector-controller.js
- hopsworks-web/yo/app/scripts/services/filemgr/filenavigator.js
[HOPSWORKS-976]  Fix bug with updating project ID when navigating to another project
[HOPSWORKS-976]  Refactor filemanager service
[HOPSWORKS-976]  Fix bug with file manager when refreshing
https://logicalclocks.atlassian.net/browse/HOPSWORKS-976
Bug fix
> [HOPSWORKS-976]  Fix bugs with angular file manager for Airflow

- hopsworks-web/yo/app/views/profile.html
> [HOPSWORKS-979] fix change password problem

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/styles/style.css
- hopsworks-web/yo/app/views/jobs.html
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-932
> HOPSWORKS-932

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowJWTManager.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-966
New feature
Integrate Apache Sqoop to Hopsworks and Airflow by creating a wrapper Operator around SqoopOperator. Also, change to username for the input of the digest for the private directory in Airflow
> [HOPSWORKS-966] Airflow/Sqoop integration with Hopsworks

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/Project.java
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/loginCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/services/TourService.js
- hopsworks-web/yo/app/views/home.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/newJob.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-197
Implementation of this JIRA introduces the following:
1. drop-down list is now open be default
2. Tour tips are enabled be default
3. When a tour finishes, tour tips for all tours are disabled.
In a next PR, we can introduce project specific tour state as it's now done only at user level.
> HOPSWORKS-197

- README.md
- hopsworks-IT/pom.xml
> [HOPSWORKS-759] Append. fix readme

- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
> [HOPSWORKS-716] Append. Update Jupyter baseDir in the frontend

- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-716] - append - fix license header

- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/styles/style.css
- hopsworks-web/yo/app/views/datasetsBrowser.html
Fix datasetsbrowser padding and remove job entries from localstorage.
> [HOPSWORKS-932] append

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/OSProcessExecutor.java
[HOPSWORKS-988]  Fix bug with timed out OS process 
[HOPSWORKS-988]  Fix retry mechanism for starting Jupyter server
https://logicalclocks.atlassian.net/browse/HOPSWORKS-988
Bug fix
> [HOPSWORKS-988]  Fix bug with timed out OS process and starting Jupyter

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/ClusterUtilisationService.java
- hopsworks-web/yo/app/nav.html
- hopsworks-web/yo/app/scripts/app.js
- hopsworks-web/yo/app/scripts/controllers/fileUploadCtrl.js
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/services/AuthGuardService.js
- hopsworks-web/yo/app/scripts/services/AuthInterceptorService.js
- hopsworks-web/yo/app/scripts/services/AuthService.js
- hopsworks-web/yo/app/styles/style.css
- hopsworks-web/yo/app/views/home.html
- hopsworks-web/yo/app/views/login.html
- hopsworks-web/yo/app/views/project.html
- hopsworks-web/yo/app/views/projectsPanel.html
- hopsworks-web/yo/app/views/toursPanel.html
> [HOPSWORKS-990] fix jwt concurrent access problem

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardController.java
…tensorflow-gpu is in the project environment
> [HOPSWORKS-994] TensorBoard in experiments service fails to start if tensorflow-gpu is in the project environment

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-996
Bug fix
> [HOPSWORKS-996]  Fix bug with creating log copying threads

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-716] Append - Export missing env vars, tour should not reset configuration, min executors to 0 for dist training

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/jobhistory/JobState.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1004
Bug fix
> [HOPSWORKS-1004] Add GENERATING_SECURITY_MATERIAL to the list of running states for jobs

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/jobhistory/JobState.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1004
Bug fix
> [HOPSWORKS-1004]  Add GENERATING_CERTS to the list of running states for jobs

- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsDirectoryWithQuotaFeature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsDirectoryWithQuotaFeatureFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
> [HOPSWORKS-1011] hops-metadata-dal-impl-ndb schema update renames hdfs_inode_attributes to hdfs_directory_with_quota_feature

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/views/sparkConfig.html
> [HOPSWORKS-1002] MirroredStrategy should support multi-worker

- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/wscomm/WebSocketEndpoint.java
- hopsworks-web/yo/app/scripts/services/MetadataService.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1012
Bug fix
> [HOPSWORKS-1012]  Fix metadata designer

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowMaterial.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowMaterialFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowMaterialID.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-999
New feature
Airflow security material will survive from Hopsworks restart
> [HOPSWORKS-999] Airflow recovery

- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
> [HOPSWORKS-1003] Jupyter convert notebook should inject SparkSession and handle spaces in notebook name

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
> [HOPSWORKS-1009] fix cross-origin policy for files and view endpoints in jupyter notebook

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-jwt/src/main/java/io/hops/hopsworks/jwt/filter/JWTFilter.java
> [HOPSWORKS-915] Reduce info logging at user login

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
> [HOPSWORKS-875] Add PyTorch, Torchvision and Matplotlib to python base environment

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsDirectoryWithQuotaFeature.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HOPSWORKS-1011] Append - additional hdfs_directory_with_quota_feature column renames

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/FeaturestoreController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1017
Bug fix
No
> [HOPSWORKS-1017] Bugfix: date creation is NaN

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnLogUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1022
Bug fix
> [HOPSWORKS-1022]  Fix bug with log aggregation status NOT_START

- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-904] Users should be able to specify version of Python library to install when behind PyPi proxy

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/execution_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
Feature store tests failure is detected before timeout.
> [HOPSWORKS-718] Append, update feature store tests

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobScheduler.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/ThrowableMapper.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1031
RESTException dev messages were not logged in glassfish
https://github.com/logicalclocks/hops-testing/pull/354
> [HOPSWORKS-1031] Fix logging and add proper conda message

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/tensorflow/TensorBoardService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TensorBoard.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardKillTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/exceptions/TensorBoardException.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-1001] Experiments service refactor certificates cleanup

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jobhistory/Execution.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobScheduler.java
> [HOPSWORKS-1036] JobScheduler gets expunged when trying to start an execution for a job while the job is still running

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1041
Bug fix
> [HOPSWORKS-1041]  Fix Metadata upload

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
Reverts logicalclocks/hopsworks#203
> Revert "[HOPSWORKS-1041]  Fix Metadata upload"

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
Testing: https://github.com/logicalclocks/hops-testing/pull/362
> [HOPSWORKS-1043] addUserToGroup throws exception if user is added twice

- hopsworks-IT/src/test/ruby/spec/helpers/python_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/session_helper.rb
- hopsworks-IT/src/test/ruby/spec/hops_util_py_it_spec.rb
- hopsworks-IT/src/test/ruby/spec/spec_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-998
Tests
Integration tests for hops-util-py
Attributed in karamel control whether the integration tests will be run (by default they will not run)
> [HOPSWORKS-998] [hops-util-py] Tests

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/pythonDeps/PythonDepsService.java
Also, use capital letters in tests for random project names
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1048
Bug fix
> [HOPSWORKS-1048]  Lowercase project name when creating index at Elasticsearch for kagent logs

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/views/sparkConfig.html
> [HOPSWORKS-954] Add support for ROCm

- hopsworks-IT/src/test/java/io/hops/hopsworks/LoginIT.java
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/loginCtrl.js
> [HOPSWORKS-1040] fix growl

- hopsworks-cluster/src/main/webapp/package.json
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1067
Bug fix
> [HOPSWORKS-1067] Remove broken dependency

- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
> [HOPSWORKS-1040] append

- hopsworks-IT/src/test/ruby/Gemfile
- hopsworks-IT/src/test/ruby/spec/spec_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1074
new feature
> [HOPSWORKS-1074] Use new hops-airborne library with http timeout option

- hopsworks-web/yo/app/scripts/controllers/experimentsCtrl.js
- hopsworks-web/yo/app/views/experiments.html
> [HOPSWORKS-991] Add new windows button to experiments

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/views/sparkConfig.html
> [HOPSWORKS-1077] Review overridable Spark configuration properties for SparkJobConfiguration

- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/MaterializedJWT.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/MaterializedJWTFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/MaterializedJWTID.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTManager.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1068
New feature
> [HOPSWORKS-1068] JWT for Jupyter Notebook servers

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/oauth/OAuthClientRegistration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/remote/oauth/OauthClient.java
- hopsworks-web/yo/app/views/remoteUserConsentModal.html
> [HOPSWORKS-1019] append

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/FeaturestoreEntityDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/app/FeaturestoreMetadataDTO.java
- also enable feature store %%local clients to make REST requests to Hopsworks
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1024?filter=-1
feature
optimize feature store rest calls and also make the rest calls possible from %%local
no
> [HOPSWORKS-1024][featurestore] optimize metadata

- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
> [HOPSWORKS-762] append fix new job

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/EndpointService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsLeDescriptors.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsLeDescriptorsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
> [HOPSWORKS-1070] Refactor HdfsLeDescriptorsFacade to return a random NN for bootstrapping the client

- hopsworks-web/yo/app/views/ldapLogin.html
- hopsworks-web/yo/app/views/login.html
> [HOPSWORKS-1082] Remove Beta

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/selectFileCtrl.js
- hopsworks-web/yo/app/views/newJob.html
fix job artifact selector. fix moving multiple files error growl. 
Remove hdfs:// from job_helper ruby.
> [HOPSWORKS-1014] append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/TfLibMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tensorflow/TfLibMappingUtil.java
> [HOPSWORKS-1087] Fix nested transaction exception when starting jupyter

- hopsworks-common/src/main/java/io/hops/hopsworks/common/tensorflow/TfLibMappingUtil.java
>  [HOPSWORKS-1052] Upgrading ROCm, Pydoop

- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HOPSWORKS-1090] TensorBoardController nested transaction exception

- README.md
- hopsworks-IT/src/test/java/io/hops/hopsworks/LoginIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/RegisterIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/admin/VariablesIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/util/Helpers.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/maintenance/MaintenanceBean.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesMgmService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/createAclCtrl.js
- hopsworks-web/yo/app/scripts/controllers/loginCtrl.js
- hopsworks-web/yo/app/views/login.html
- scripts/create_project_as_user.py
> [HOPSWORKS-672] Replace admin email

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/hopsfs_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/inode/InodeFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnExecutionFinalizer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/MoreInfoDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1064] After HOPS-1215, small files are a storage type

- hopsworks-web/yo/app/scripts/services/TourService.js
> [HOPSWORKS-1014] append - Fix kafka tour jar path

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1088
bugfix
no
Tests: https://github.com/logicalclocks/hops-testing/pull/397
> [HOPSWORKS-1088] revise cert management for featurestore

- hopsworks-IT/src/test/ruby/spec/jwt_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1101
Bug fix
> [HOPSWORKS-1101] Fix JWT test after chaning default user account

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJobConfiguration.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
> [HOPSWORKS-1083] Enable conda by default

- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-762] append fix error code

- README.md
- hopsworks-IT/src/test/java/io/hops/hopsworks/LoginIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/RegisterIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/admin/VariablesIT.java
- hopsworks-IT/src/test/java/io/hops/hopsworks/util/Helpers.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- scripts/create_project_as_user.py
> [HOPSWORKS-672] append - replace admin@hopsworks.com with admin@hopsworks.ai

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/HDFSUIProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/EndpointService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsLeDescriptors.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/hdfs/HdfsLeDescriptorsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1099] Get leader NN http address automatically from hdfs_le_descriptors

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/search/LibrarySearchBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/search/LibrarySearchDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
> [HOPSWORKS-1106] Conda search versions not sorted

- pom.xml
> [HOPSWORKS-1105] Bump hops to 2.8.2.8

- hopsworks-web/yo/app/scripts/services/TourService.js
- hopsworks-web/yo/app/views/newJob.html
> [HOPSWORKS-1014][Append] Add missing root path

- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/llap/LlapClusterLifecycle.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/FeaturestoreFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveController.java
> [HOPSWORKS-385] Add support to Hive for Hops TLS model

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/yarn/YarnClientService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1115
> [HOPSWORKS-1115] Remove deprecate code from Hadoop clients factory

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1110
Improvement
> [HOPSWORKS-1110] Change Airflow JWT audience

- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingUtil.java
- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/serving.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-751
Fix broken tests
Serving tests pass
No
> HOPSWORKS-751 append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
> [HOPSWORKS-1121] Use pip binary in base environment for search

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettingsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJobConfiguration.java
- hopsworks-web/yo/app/views/sparkConfig.html
> [HOPSWORKS-1122] Invalid JobConfiguration when EXPERIMENT is set as default

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/views/datasets.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1039
UI update
Readable names of Hive and Featurestore datasets in the UI as well as new icons
No
> [HOPSWORKS-1039][Featurestore] Make datasets more visible

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryVersionDTO.java
> [HOPSWORKS-1125] fix libraries with no release date

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/ProjectFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1047
Bug fix
https://github.com/logicalclocks/hops-testing/pull/428
> [HOPSWORKS-1147] Search results for hive datasets are not clickable

- hopsworks-web/yo/app/views/sparkConfig.html
> [HOPSWORKS-1168] GPU warning being shown in Spark Static and Spark Dynamic views

- hopsworks-IT/src/test/ruby/Gemfile
- hopsworks-IT/src/test/ruby/spec/jwt_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/DateTimeAdapter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JWTRequestDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jwt/JsonWebTokenDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1165?oldIssueView=true
Bug fix
> [HOPSWORKS-1165] Add tzinfo in (un)marshalling of Date

- hopsworks-web/yo/app/views/fileUpload.html
> [HOPSWORKS-1172] Upload progress not visible in the beginning of uploading large files

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1154] Improve creation speed for Deep Learning and Featurestore tours

- scripts/scp-deploy-frontend.sh
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1124
Improvement to the script. 
Reduced the time from ~90 seconds to ~20 seconds.
> [HOPSWORKS-1124] optimize scp-deploy-frontend.sh

- hopsworks-IT/src/test/ruby/spec/admin_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1197
Bug fix
> [HOPSWORKS-1197] Reset session after running admin tests

- hopsworks-web/yo/.bowerrc
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/bower.json
- hopsworks-web/yo/package.json
- scripts/js.sh
- scripts/scp-deploy-frontend.sh
- upgrade apexcharts
- remove npm resolver
- move apexcharts to node_modules
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1200
optimize web build
new apexcharts version, drop npm-resolver
No
> [HOPSWORKS-1200] upgrade apexcharts

- hopsworks-IT/pom.xml
- hopsworks-IT/src/test/ruby/spec/activity_spec.rb
- hopsworks-IT/src/test/ruby/spec/users_spec.rb
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-rest-utils/src/test/java/io/hops/hopsworks/TestRESTCodes.java
> [HOPSWORKS-1199] ErrorCode range mismatch and TestRestCodes not testing all ErrorCodes

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- add back hopsworks_project_id env variable for jupyter config
> [HOPSWORKS-1164] append

- hopsworks-IT/src/test/ruby/.env.example
- hopsworks-IT/src/test/ruby/spec/spec_helper.rb
> [HOPSWORKS-1063] update .env.example to not use mysql.sock

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-IT/src/test/ruby/spec/dela_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/ca_helper.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
> [HOPSWORKS-1207] Hopsworks broken on Ubuntu 18.04

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1181] Remove hopsfacets

- hopsworks-common/src/main/java/io/hops/hopsworks/common/tensorflow/TfLibMappingUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
> [HOPSWORKS-1119] Upgrade ROCm to 2.6 and tensorflow-rocm 1.14

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
> [HOPSWORKS-1207] append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/livy/LivyController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/resources/io/hops/jupyter/config_template.json
> [HOPSWORKS-1228] Remove livy session name from sparkmagic conf file

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/FeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/on_demand_featuregroup/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/settings/FeaturestoreClientSettingsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/storageconnector/hopsfs/FeaturestoreHopsfsConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/storageconnector/jdbc/FeaturestoreJdbcConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/storageconnector/s3/FeaturestoreS3ConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdataset/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdataset/external_trainingdataset/ExternalTrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdataset/hopsfs_trainingdataset/HopsfsTrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featorestore/FeaturestoreConstants.java
- Extract constants from DTO to its own class
- Fix failing tests
> [HOPSWORKS-1196][featurestore] append

- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/KafkaFacade.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-909
upgrade Kafka to version 2.3
> [HOPSWORKS-909] Upgrade Kafka to 2.3.0

- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1176] Remove admin password useless methods

- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1236
Bug fix
> [HOPSWORKS-1236] Fix bug in Project cleanup after a failed creation

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/client/HttpClient.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1239
Task
Make a REST call to Jupyter's API to check if it's running instead of executing a `ps` from a bash script
> [HOPSWORKS-1239] Use Jupyter server API to ping instead of using the bash script

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/security/apiKey/ApiScope.java
> HOPSWORKS-1231

- hopsworks-IT/pom.xml
- hopsworks-IT/src/test/java/io/hops/hopsworks/WebDriverFactory.java
> [HOPSWORKS-1207] fix chromedriver version

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-web/yo/app/views/userSettings.html
> [HOPSWORKS-901] Fix active projects UI and error message.

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-api/src/main/webapp/WEB-INF/beans.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/GitConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/integrations/NullJupyterNbVCSStereotype.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterContentsManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NullJupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/RepositoryStatus.java
- hopsworks-common/src/main/resources/META-INF/beans.xml
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/services/JupyterService.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/sparkConfig.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1243
New feature
No changes for the Community Edition. For Enterprise Edition Git backend for Jupyter Notebook server
> [HOPSWORKS-1243] Community edition Jupyter server support for Git

- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/CAProxy.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1263
Bug fix
> [HOPSWORKS-1263] Fix bug when revoking certificate that does not exist

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentLivenessMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1261
Task
> [HOPSWORKS-1261] Do not use bash scripts to start/stop kagent remotely

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/CachedFeaturegroupController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- Integrate hudi with feature store service
https://logicalclocks.atlassian.net/browse/HOPSWORKS-34
Feature
Support Hudi feature groups in the Feature store Service
No
> [HOPSWORKS-34] Hudi for unified Stream/Batch processing

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/apiKey/ApiKeyFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/search/LibrarySearchBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryController.java
- hopsworks-kmon/src/main/webapp/monitor/anaconda.xhtml
> [HOPSWORKS-1268] Sanitize python library name/version/reposity/url

- LICENSE_OF_DEPENDENCIES.md
- hopsworks-common/pom.xml
- pom.xml
> [HOPSWORKS-1271] Bump hive version to 3.0.0.2

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/ExecutionController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
> [HOPSWORKS-1195] Sanitize local resources

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentYmlDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/scripts/services/PythonService.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/python.html
- hopsworks-web/yo/app/views/selectEnvYml.html
…licit enabling of python kernel
> [HOPSWORKS-1276] Anaconda import yml file not working, removal of explicitly enabling python kernel

- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-1284] add install lib without search

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/DataValidationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/datavalidation/ConstraintDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/datavalidation/ConstraintGroupDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/json/datavalidation/DataValidationSettingsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/Constraint.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/ConstraintGroup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/ConstraintGroupLevel.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/ConstraintResult.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/DataValidationController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/datavalidation/ValidationResult.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/app.js
- hopsworks-web/yo/app/scripts/controllers/dataValidationCtrl.js
- hopsworks-web/yo/app/scripts/controllers/dataValidationModalsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
- hopsworks-web/yo/app/scripts/services/DataValidationService.js
- hopsworks-web/yo/app/scripts/services/ModalService.js
- hopsworks-web/yo/app/views/addDataValidationPredicate.html
- hopsworks-web/yo/app/views/dataValidation.html
- hopsworks-web/yo/app/views/featurestore.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1265
New feature
> [HOPSWORKS-1265] Feature store data validation

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/AccessCredentialsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/CertsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
> [HOPSWORKS-1293] Add credential endpoint

- hopsworks-web/yo/app/scripts/controllers/servingCtrl.js
- hopsworks-web/yo/app/views/serving.html
> [HOPSWORKS-1297] Model Serving view not sorted

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NullJupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/RepositoryStatus.java
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/services/JupyterService.js
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/sparkConfig.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1208
New feature
> [HOPSWORKS-1208] JupyterLab/Git integration

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featorestore/FeaturestoreConstants.java
Configure JDBC to be one of the legal connectors for importing
feature data.
> [HOPSWORKS-1301] Enable feature import via JDBC

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
> [HOPSWORKS-1140][online featurestore] append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/importjob/FeaturegroupImportJobDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/importjob/ImportType.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkCompletedJobsCache.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
Add support for importing to the online featurestore and from redshift
> [HOPSWORKS-1304] - append - add support for online import and redshift

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-common/src/main/resources/io/hops/jupyter/jupyter_notebook_config_template.py
Add ca truststore pem in spark executors
> [HOPSWORKS-1021] Python requests 

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/ImportControllerIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobControllerIface.java
> [HOPSWORKS-1304] append - change exception type

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/DataValidationResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AuthFilter.java
- hopsworks-jwt/src/main/java/io/hops/hopsworks/jwt/filter/JWTFilter.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1312
> [HOPSWORKS-1312] Allow users to access data validation API with API key

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1299] append

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-640] Add conda env in dynamic properties

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/DataSetService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/FsPermissions.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/HopsUtils.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1315
Bug fix
> [HOPSWORKS-1315] Fix bug with default umask in DFS client

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectMembersService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/FeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/online_featuregroup/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/online_featurestore/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1325
Bug fix
> [HOPSWORKS-1325] Convert all Online Featurestore DB names to lowercase and fix adding member to a Project

- hopsworks-IT/src/test/ruby/spec/users_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1325
Tests bug fix
> [HOPSWORKS-1325] Fix broken Secrets tests

- hopsworks-web/yo/app/views/dataValidation.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1360
Bug fix in UI
> [HOPSWORKS-1360] Include properly mainCtrl at data validation page

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VersionsDTO.java
> [HOPSWORKS-1364] remove telegraf and kapacitor from VersionsDTO

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ElasticSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1027
testing: https://github.com/logicalclocks/hops-testing/pull/512
> [HOPSWORKS-1027] Add support for multiple elasticsearch nodes (HA)

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1338
> [HOPSWORKS-1338] [featurestore] Configurable in-bucket path for exporting training datasets to S3

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdatasetjob/TrainingDatasetJobDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1334
Adds the possibility to create a training dataset job from a SQL query string through the REST endpoint.
> [HOPSWORKS-1334][hopsworks-cloud-sdk] SQL query for creating training datasets

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/feature/FeatureDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1363
feature
Track feature groups used to create a training dataset
> [HOPSWORKS-1363][featurestore] feature provenance for training datasets

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/cached_featuregroup/CachedFeaturegroupFacade.java
- hopsworks-web/yo/app/scripts/controllers/newFeaturegroupCtrl.js
- hopsworks-web/yo/app/views/newFeaturegroup.html
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-1378?filter=myopenissues
feature
support composite keys for feature groups in the backend
No
> [HOPSWORKS-1378][featurestore] DDL enable composite keys

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/hopsfs_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/python_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- tools/conda/python3.6.yml
> [HOPSWORKS-1305] Fix broken Anaconda export yml

- hopsworks-IT/src/test/java/io/hops/hopsworks/WebDriverFactory.java
> upgrade chrome driver

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
Throw an exception when attempting to create a feature group
that is already existing.
> [HOPSWORKS-1318] Fail on duplicated create

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/message/Message.java
> [HOPSWORKS-1388] Text to varchar

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/ApplicationConfig.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/CRLResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/CertificatesResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/CAConf.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1395
Endpoint to fetch intermediate HopsCA CRL
Change CRL fetcher configuration in core-site.xml to new endpoint
> [HOPSWORKS-1395] Add CA endpoint to download HopsCA CRL

- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/services/AuthService.js
- hopsworks-web/yo/app/scripts/services/TourService.js
- hopsworks-web/yo/app/views/createTopic.html
- hopsworks-web/yo/app/views/datasets.html
- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/home.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/kafka.html
- hopsworks-web/yo/app/views/newJob.html
- hopsworks-web/yo/app/views/schemaCreate.html
- hopsworks-web/yo/app/views/toursPanel.html
> [HOPSWORKS-1194]

- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1408
Bug fix
> [HOPSWORKS-1408] Do not throw Exception during initialization of AirflowManager

- hopsworks-admin/src/main/webapp/security/protected/admin/newUsers.xhtml
- hopsworks-admin/src/main/webapp/security/protected/admin/spamUsers.xhtml
- hopsworks-admin/src/main/webapp/security/protected/admin/userAdministration.xhtml
> [HOPSWORKS-1398] date pattern

- hopsworks-web/yo/app/views/jupyter/experimentConfig.html
> [HOPSWORKS-1389] Append experiment configuration only showing on machine with GPUs

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1431
Bug fix
> [HOPSWORKS-1431] Do not throw Jupyter/Git exception if it's shutting down quietly

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/Featuregroup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/statisticcolumns/StatisticColumn.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/statisticcolumns/StatisticColumnController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/statisticcolumns/StatisticColumnFacade.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-web/yo/app/scripts/controllers/updateFeaturestoreStatisticModalCtrl.js
- hopsworks-web/yo/app/scripts/services/FeaturestoreService.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1380
https://bbc1.sics.se/jenkins/job/HopsWorks-testing/1981/
No breaking changes, old clients will still work.
> [HOPSWORKS-1380][featurestore] Configure Feature Group statistics during creation

- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/views/jupyter/sparkConfig.html
> [HOPSWORKS-1389] Append scope watches overwrite job configuration

- hopsworks-IT/src/test/ruby/spec/admin_spec.rb
- hopsworks-IT/src/test/ruby/spec/agent_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterMode.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1433
Task
> [HOPSWORKS-1433] Add option to start JupyterLab or Jupyter classic

- hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/updateFeaturestoreStatisticModalCtrl.js
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1442
Front end was using the wrong attribute of an object.
> [HOPSWORKS-1442] Fix update statistics job showing app file as undefined

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/profile/AdminProfileAdministration.java
- hopsworks-admin/src/main/webapp/security/protected/admin/admin_profile.xhtml
> [HOPSWORKS-1415][append] only show dialog if password changed

- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/inference/logger/KafkaInferenceLogger.java
> [HOPSWORKS-1303][append] Fix inference kafka producer

- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/styles/board.css
- hopsworks-web/yo/app/views/jupyter/experimentConfig.html
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
- hopsworks-web/yo/app/views/jupyter/pythonConfig.html
- hopsworks-web/yo/app/views/jupyter/sparkConfig.html
> [HOPSWORKS-1389] Append doc links not clickable, advanced not saved

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
> [HOPSWORKS-229][append] fix multiple confirm dialog on delete

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/KernelTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/KernelTemplateBuilder.java
> [HOPSWORKS-1434] Scale jvm -Xmx for Spark and Jupyter based on allocated memory

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/xattrs_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/wscomm/MetadataController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/MetadataService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1422
tests: https://github.com/logicalclocks/hops-testing/pull/546
> [HOPSWORKS-1422] Custom metadata to featuregroups

- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/ElasticService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticUtils.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1476
tests: https://github.com/logicalclocks/hops-testing/pull/567
> [HOPSWORKS-1476] Add support for elasticsearch spark connector

- hopsworks-web/yo/app/views/datasets.html
> [HOPSWORKS-229]-append fix eye not showing

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
> [HOPSWORKS-1479] Enable all Jupyter kernels by default

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1484
> [HOPSWORKS-1484] Shared feature stores do not appear in the UI

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/TopicDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/util/KafkaServingHelper.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1498
bug fix
> [HOPSWORKS-1498] hops-util-py can't find attributes in KafkaTopicDTO

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
> [HOPSWORKS-229] Fixes for datasets browser buttons and converting notebooks

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/KibanaClient.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1490
> [HOPSWORKS-1490] Handle Kibana failures in Hopsworks Kibana client

- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/app/dto/ProvAppStateElastic.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/state/dto/ProvStateElastic.java
- hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaDatasetController.java
> [HOPSWORKS-1467][append] min provenance

- pom.xml
> [HOPSWORKS-1499] Bump Hops version to 2.8.2.9

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ElasticSettings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1372] Append ElasticJWTExpMs should be long not int

- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsController.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/ExperimentsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-web/yo/app/scripts/controllers/experimentCtrl.js
- hopsworks-web/yo/app/scripts/controllers/modelViewInfoCtrl.js
> [HOPSWORKS-1109] Append use jupyterhost for versioning, fix nullpointer and don't fail experiment if notebook could not be versioned

- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
Fixes for jobsToDate and remove redundant modal for stopping a job
> [HOPSWORKS-1356][append] Fix job date and modal

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/app.js
- hopsworks-web/yo/app/scripts/controllers/featureListCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featureViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featuregroupViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newFeaturegroupCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/selectFeatureTypeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/trainingDatasetViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/directives/featureList.js
- hopsworks-web/yo/app/scripts/services/FeaturestoreService.js
- hopsworks-web/yo/app/scripts/services/ModalService.js
- hopsworks-web/yo/app/styles/featurestore.css
- hopsworks-web/yo/app/views/dagComposer.html
- hopsworks-web/yo/app/views/dataValidation.html
- hopsworks-web/yo/app/views/featureList.html
- hopsworks-web/yo/app/views/featureViewInfo.html
- hopsworks-web/yo/app/views/featuregroupViewInfo.html
- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/newFeaturegroup.html
- hopsworks-web/yo/app/views/newTrainingDataset.html
- hopsworks-web/yo/app/views/selectFeatureType.html
- hopsworks-web/yo/app/views/trainingDatasetViewInfo.html
- scripts/scp-deploy-frontend.sh
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1494
> [HOPSWORKS-1494] Feature store UI improvements

- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
> [HOPSWORKS-1356][append] Fix Kibana logs in Jobs UI

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/FolderNameValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1474
Read reserved Project names from the Variables table instead of hardcoding them
> [HOPSWORKS-1474] Read reserved project names from Settings instead of hard-coding them

- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
> [HOPSWORKS-1356][append] Fix stdout stderr logs refresh issue

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticJWTController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- [*] HOPSWORKS JIRA issue has been opened for this PR
- [*] All commits have been squashed down to a single commit
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1510
bug fix
> [HOPSWORKS-1510] remove the code to delete index patterns since we delete kibana project index

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
> [HOPSWORKS-1353] Flink timer should handle case when service is not installed

- hopsworks-IT/src/test/ruby/spec/factories/inode.rb
- hopsworks-IT/src/test/ruby/spec/jwt_spec.rb
- hopsworks-jwt/src/main/java/io/hops/hopsworks/jwt/JWTController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1519
Bug fix
tests: https://github.com/logicalclocks/hops-testing/pull/594
> [HOPSWORKS-1519] The subject of ELK JWT token should be always lowercase

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/views/datasetsBrowser.html
> [HOPSWORKS-1521] Dataset browser refresh button not working

- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ProvenanceCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/maggy/MaggyCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hive/HiveScratchdirCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJobsMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNotebookCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jwt/InvalidatedJWTCleanup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jwt/OneTimeJWTRotation.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/ZookeeperTopicCleanerTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/ServiceCertificateRotationTimer.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/monitor/LocalhostServingMonitor.java
- hopsworks-dela/src/main/java/io/hops/hopsworks/dela/DelaSetupWorker.java
> [HOPSWORKS-1379] Timers should be rescheduled when failed and handle exceptions

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/maintenance/NodesBean.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/hosts/HostsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentLivenessMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/Hosts.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/HostsFacade.java
> [HOPSWORKS-1483][append] Refactor Admin API - Hosts

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1534
bug fix
https://github.com/logicalclocks/hops-testing/pull/599
> [HOPSWORKS-1534] Kibana error when recreating the project enviroment

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/Featuregroup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/featuregroup/ondemand/OnDemandFeaturegroup.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdataset/TrainingDataset.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/featurestore/trainingdataset/external/ExternalTrainingDataset.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreEntityDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/ondemand/OnDemandFeaturegroupDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/external/ExternalTrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/hopsfs/HopsfsTrainingDatasetController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1481
> [HOPSWORKS-1481] Add endpoints to retrieve feature groups and training datasets by name

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/KibanaClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/client/NotFoundClientProtocolException.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1534
tests: https://github.com/logicalclocks/hops-testing/pull/607
> [HOPSWORKS-1534] append

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1544
Changes endpoint to get featurestore by name
Fixes bug introduced by HOPSWORKS-1481
> [HOPSWORKS-1544] Add endpoint to retrieve featurestore by name

- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/prov_state_notebooks_spec.rb
> [HOPSWORKS-1467][amend] Min provenance test fixes

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1544
Fixes a problem with the previous PR
> [HOPSWORKS-1544][append] Fix endpoint audience

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-web/yo/app/views/datasetsBrowser.html
> [HOPSWORKS-1283] Zip does not work when there is a space in the file path

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowDag.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowDagFacade.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1551
Feature request
> [HOPSWORKS-1551] Do not use a Persistence Unit for the optional Airflow database

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/ndb/NdbBackupBean.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/agent/AgentResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/CAConf.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/OpensslOperations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/admin/llap/LlapClusterLifecycle.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/monitor/LocalhostServingMonitor.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1257] sudoers script should be owned by root and 700

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
…during cleanup
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1545
Bugfix
tests: https://github.com/logicalclocks/hops-testing/pull/612
> [HOPSWORKS-1545] Handle cases where Elasticsearch is down

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/?filter=myopenissues
bug fix
> [HOPSWORKS-1354] change metadata template upload path from /Projects/Uploads to /user/metadata/uploads

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
> [HOPSWORKS-1536] Fix rename, rephrase remove

- hopsworks-IT/src/test/ruby/spec/helpers/prov_state_helper.rb
- hopsworks-IT/src/test/ruby/spec/prov_state_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ProjectProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/state/ProvFileStateBeanParam.java
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleaner.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleanerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-testing/src/main/java/io/hops/hopsworks/testing/ApplicationConfig.java
- hopsworks-testing/src/main/java/io/hops/hopsworks/testing/provenance/TestProjectProvenanceResource.java
- hopsworks-testing/src/main/java/io/hops/hopsworks/testing/provenance/TestProvenanceService.java
transaction fix, move to timer service, tests
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1553
Bug fix
> [HOPSWORKS-1553] provenance cleaner timer

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
Reverts logicalclocks/hopsworks#454
> Revert "[HOPSWORKS-1545] Handle cases where Elasticsearch is down"

- hopsworks-web/yo/app/scripts/controllers/sharedSchemaViewContentCtrl.js
- hopsworks-web/yo/app/views/sharedSchemaViewContent.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1563
bug fix
schema is beautified 
> [HOPSWORKS-1563] Schema of a shared topic is shown in one line

- README.md
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/security/ua/LoginBean.java
- hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/user/LoginBean.java
- hopsworks-web/yo/app/views/ldapLogin.html
- hopsworks-web/yo/app/views/login.html
- hopsworks-web/yo/app/views/toursPanel.html
> [HOPSWORKS-1522] Change support link

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
> [HOPSWORKS-1565] delete shared dataset

- hopsworks-common/src/main/java/io/hops/hopsworks/common/airflow/AirflowManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowDagFacade.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1551
See https://github.com/logicalclocks/hopsworks/pull/464
> [HOPSWORKS-1551] Make a dummy query in startup to initialize connection pool metrics

- README.md
> [HOPSWORKS-1572] Add swagger doc

- hopsworks-web/yo/app/views/jupyter/commonTooltips.html
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
> [HOPSWORKS-1575] Update old readthedocs link

- hopsworks-IT/src/test/ruby/spec/session_spec.rb
- hopsworks-cluster/src/main/java/io/hops/hopsworks/cluster/controller/ClusterController.java
> [HOPSWORKS-1382]-append fix build with cluster

- hopsworks-web/yo/app/navProject.html
> [HOPSWORKS-1579] fix alignment

- hopsworks-web/yo/app/styles/dropdown-submenu.css
> [HOPSWORKS-1557] fix dropdown submenu hidden

- hopsworks-web/yo/app/scripts/controllers/jobUICtrl.js
> [HOPSWORKS-1527][Append] undefined function causes TensorBoard to not load properly

- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
> [HOPSWORKS-1382][append] fix login audit

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/UploadService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
> [HOPSWORKS-1589] Upload in shared Datasets

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/host/Status.java
> [HOPSWORKS-1600] Add missing kagent enum entry

- hopsworks-kmon/src/main/java/io/hops/hopsworks/kmon/communication/CommunicationController.java
> [HOPSWORKS-1599] Add missing getter/setter for serviceInstancesController

- hopsworks-IT/pom.xml
- hopsworks-IT/src/test/java/io/hops/hopsworks/WebDriverFactory.java
> [HOPSWORKS-1605] fix chrome version and disable some tests 

- hopsworks-IT/src/test/ruby/spec/helpers/kafka_helper.rb
- hopsworks-IT/src/test/ruby/spec/kafka_acl_spec.rb
- hopsworks-IT/src/test/ruby/spec/kafka_spec.rb
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/SharedTopics.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/SharedTopicsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/TopicDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/KibanaClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-web/yo/app/scripts/controllers/kafkaCtrl.js
- hopsworks-web/yo/app/scripts/services/KafkaService.js
- hopsworks-web/yo/app/views/kafka.html
> [HOPSWORKS-1567] Add a confirmation when sharing a kafka topic with another project

- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnRunner.java
- hopsworks-dela/pom.xml
> [HOPSWORKS-1493] Bump flink

- hopsworks-common/pom.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1645
Bug fix
> [HOPSWORKS-1645] fix duplicated class

- hopsworks-web/yo/app/scripts/controllers/experimentCtrl.js
> [HOPSWORKS-1646] Leftover state when updating experiments table

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/tensorboard/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/tensorflow/TfLibMappingUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1530] Upgrade TensorFlow to 1.15.0

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFileSystemOps.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1409
feature 
> [HOPSWORKS-1409] chef configurable hdfs storage policy

- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/project/Project.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1653
bug fix
typo fixes:
double Collection in var name in Project
use of user (bad variable name) in Settings setVar
> [HOPSWORKS-1653] provenance print issue - lower case hivedb name

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
> [HOPSWORKS-1619] add test for zip/unzip with url encoded chars in dir name

- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newFeaturegroupCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js
> [HOPSWORKS-1654] Feature store page stuck in loading view if project name contains upper case letters

- hopsworks-admin/pom.xml
- hopsworks-api/pom.xml
- hopsworks-kmon/pom.xml
- hopsworks-persistence/pom.xml
> [HOPSWORKS-1607]-append reduce ear size

- hopsworks-web/yo/app/views/airflow.html
- hopsworks-web/yo/app/views/experiments.html
- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
- hopsworks-web/yo/app/views/kafka.html
- hopsworks-web/yo/app/views/metadata.html
- hopsworks-web/yo/app/views/models.html
- hopsworks-web/yo/app/views/projectSettings.html
- hopsworks-web/yo/app/views/python.html
- hopsworks-web/yo/app/views/serving.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1650
ui fix
> [HOPSWORKS-1650] search results in all service pages

- hopsworks-web/yo/app/scripts/services/DataSetService.js
> [HOPSWORKS-1612] fix url encoded chars in dir name

- pom.xml
> [HOPSWORKS-1660] Bump hops to 2.8.2.10-SNAPSHOT

- hopsworks-web/yo/app/scripts/controllers/featureListCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featureViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featuregroupViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newFeaturegroupCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/trainingDatasetViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/directives/featureList.js
- hopsworks-web/yo/app/scripts/services/ModalService.js
- hopsworks-web/yo/app/styles/featurestore.css
- hopsworks-web/yo/app/styles/nav.css
- hopsworks-web/yo/app/views/datasetsBrowser.html
- hopsworks-web/yo/app/views/featureList.html
- hopsworks-web/yo/app/views/featureViewInfo.html
- hopsworks-web/yo/app/views/featuregroupViewInfo.html
- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/newTrainingDataset.html
- hopsworks-web/yo/app/views/trainingDatasetViewInfo.html
> [HOPSWORKS-1648] Show feature groups/training dataset/feature details in a sidebar

- hopsworks-web/yo/app/scripts/services/DatasetBrowserService.js
- hopsworks-web/yo/app/styles/style.css
- hopsworks-web/yo/app/views/selectDir.html
- hopsworks-web/yo/app/views/selectEnvYml.html
- hopsworks-web/yo/app/views/selectFile.html
> [HOPSWORKS-1664] fix select modal shared dataset name

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1668
> [HOPSWORKS-1668] Add API key annotations for StorageConnectorService

- hopsworks-web/yo/app/scripts/controllers/trainingDatasetViewInfoCtrl.js
> [HOPSWORKS-1648][Append] undefined service when deleting td

- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
> [HOPSWORKS-1696] Increase timeout for listing conda libs when creating a project

- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
Test run: https://github.com/logicalclocks/hops-testing/pull/676
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1706
Bug fix
> [HOPSWORKS-1706] Do not hardcode localhost nameserver, instead use whatever is configured in the system

- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java
> [HOPSWORKS-1682] fix download file name

- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/recoverCtrl.js
- hopsworks-web/yo/app/scripts/services/VariablesService.js
- hopsworks-web/yo/app/views/recover.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1697
tests: https://github.com/logicalclocks/hops-testing/pull/673
> [HOPSWORKS-1697] Passwrod recovery for clusters created by Hopsworks-cloud

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
ran featurestore_spec locally in VM
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1703
> [HOPSWORKS-1703] Return full entity as DTO in create taining dataset endpoint

- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
> [HOPSWORKS-1715] Create feature group from the UI does not work

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/administration/AuditedUserAdministration.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/administration/UserAdministrationController.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/profile/AdminProfileAdministration.java
- hopsworks-admin/src/main/webapp/security/protected/admin/admin_profile.xhtml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
> [HOPSWORKS-1707] fix entity cached

- hopsworks-web/yo/app/styles/hwSearch.css
- hopsworks-web/yo/app/views/search/search.html
> [HOPSWORKS-1665][amend] Fix license

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/variables_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/split/TrainingDatasetSplitDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/HdfsUsersController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDataset.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/TrainingDatasetSplit.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/views/trainingDatasetViewInfo.html
> [HOPSWORKS-1678][HOPSWORKS-1720][HOPSWORKS-1717][HOPSWORKS-1704]

- hopsworks-web/yo/Gruntfile.js
- hopsworks-web/yo/app/views/fileUpload.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
> [HOPSWORKS-1665]-append fix ui

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/tag/TagsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/tag/TagsDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/api/ResourceRequest.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/tag/FeaturegroupTagController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/tag/FeaturegroupTagControllerIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/tag/TrainingDatasetTagController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/tag/TrainingDatasetTagControllerIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/xattrs/XAttrsController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/index.html
- hopsworks-web/yo/app/scripts/controllers/featuregroupViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/controllers/featurestoreCtrl.js
- hopsworks-web/yo/app/scripts/controllers/tagsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/trainingDatasetViewInfoCtrl.js
- hopsworks-web/yo/app/scripts/directives/tags.js
- hopsworks-web/yo/app/scripts/services/FeaturestoreService.js
- hopsworks-web/yo/app/views/featuregroupViewInfo.html
- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/tags.html
> [HOPSWORKS-1675] Support for adding tags to featuregroups and training datasets

- hopsworks-UT/src/test/java/io/hops/hopsworks/TestJWTAnnotationPresent.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/JWTNotRequired.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/hopssite/RatingService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/serving/ServingConfResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/AuthService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/BannerService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/DownloadService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/EndpointService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
> [HOPSWORKS-1722] test jwt annotation

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1728
> [HOPSWORKS-1728] Register Logstash with Consul

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/Utils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
> [HOPSWORKS-1719] Fix job log subdirs

- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/mainCtrl.js
- hopsworks-web/yo/app/styles/project_sidebar.css
- hopsworks-web/yo/app/views/toursPanel.html
- scripts/scp-deploy-frontend.sh
> [HOPSWORKS-1629] add docs link in project navbar

- hopsworks-IT/src/test/ruby/spec/variables_spec.rb
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/maintenance/HopsworksVariablesBean.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/maintenance/LoggedMaintenanceHelper.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/ldap/ConfigureLdap.java
- hopsworks-admin/src/main/webapp/security/protected/admin/refreshVariables.xhtml
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/SystemAdminService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/BannerService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/VariablesService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/BbcGroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/util/Variables.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/util/VariablesVisibility.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1721
> [HOPSWORKS-1721] add visibility level to variables

- hopsworks-api/pom.xml
- hopsworks-persistence/pom.xml
- pom.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1760
> [HOPSWORKS-1760] persistence - pom refactor

- hopsworks-api/pom.xml
- pom.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1760
> [HOPSWORKS-1760] persistence pom refactor

- hopsworks-IT/src/test/ruby/spec/factories/hdfs_metadata_log.rb
- hopsworks-IT/src/test/ruby/spec/helpers/epipe_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/search_helper.rb
- hopsworks-IT/src/test/ruby/spec/search_spec.rb
- hopsworks-IT/src/test/ruby/spec/spec_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/elastic/featurestore/ElasticFeaturestoreBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/xattr/dto/FeaturestoreXAttrsConstants.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1749
rspec refactor - community
* rspec - epipe helper
* update to new tags endpoints being part of ee
* update rspec for more readable tests
* wait for epipe to consume hdfs mutations log
* rspec - search on description
* rspec - pagination on search
fix
> [HOPSWORKS-1749] - featurestore search - updated tests for tag endpoint

- hopsworks-IT/src/test/ruby/spec/experiment_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/epipe_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/experiment_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/prov_state_helper.rb
- hopsworks-IT/src/test/ruby/spec/model_spec.rb
- hopsworks-IT/src/test/ruby/spec/prov_state_notebooks_spec.rb
- hopsworks-IT/src/test/ruby/spec/prov_state_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ProjectProvenanceResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/ProvenanceCleanerController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ElasticCache.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ElasticHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/elastic/ProvElasticController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/state/ProvStateController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1566
> [HOPSWORKS-1566] index not found exception is not handled

- hopsworks-IT/src/test/ruby/spec/epipe_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/epipe_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/project_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1712
* rspec for epipe fixes (malformed operations)
> [HOPSWORKS-1712] provenance views - check inodes existance -> no inode -> no view

- README.md
- pom.xml
> HOPSWORKS-1765 archiva

- pom.xml
> HOPSWORKS-1765 amend

- hopsworks-IT/src/test/ruby/spec/conda_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/search_helper.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
> [HOPSWORKS-1764] reset base url

- hopsworks-web/yo/app/navProject.html
- hopsworks-web/yo/app/scripts/controllers/mainCtrl.js
- scripts/scp-deploy-frontend.sh
> [HOPSWORKS-1754] disable metadata designer

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificateMaterializer.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1767
> [HOPSWORKS-1767] fix race condition in certificate removal

- hopsworks-IT/src/test/ruby/spec/helpers/experiment_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/model_helper.rb
> [HOPSWORKS-1775] Bump experiments and models test job memory configuration

- hopsworks-IT/src/test/ruby/spec/users_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UserValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/Users.java
> [HOPSWORKS-1758] make email case insensitive

- hopsworks-IT/src/test/ruby/spec/users_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/user/UserFacade.java
> [HOPSWORKS-1758]-append fix tests

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
> [HOPSWORKS-1710] Add permission inheritance configuration to hive-site

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1781
Bug fix
> [HOPSWORKS-1781] Reuse service discovery client

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/HopsKafkaAdminClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/util/KafkaServingHelper.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> HOPSWORKS-1740 periodically ping Kafka

- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1667
fix
xattr are limited to 13500 in size, if adding features goes above this limit we skip attaching features. This means the tds and fgs will not be searchable by their feature components and the features will also not be searchable.
> [HOPSWORKS-1667][append] skip attaching features to fgs and tds if the xattr is too large

- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jobs.html
Add back job status and fix Python job appfile in More menu
> HOPSWORKS-1680 amend Add back status

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-IT/src/test/ruby/spec/search_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/DatasetController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/scripts/controllers/shareDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/unshareDatasetCtrl.js
- hopsworks-web/yo/app/views/confirmShareModal.html
- hopsworks-web/yo/app/views/shareDataset.html
- hopsworks-web/yo/app/views/unshareDataset.html
> [HOPSWORKS-1708] share td when sharing fs

- LICENSE_OF_DEPENDENCIES.md
- pom.xml
> HOPSWORKS-1787 Bump hops to 2.8.2.10-RC0

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/kafka/HopsKafkaAdminClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/util/KafkaServingHelper.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
Reverts logicalclocks/hopsworks#560
> Revert "HOPSWORKS-1740 periodically ping Kafka"

- hopsworks-web/yo/app/scripts/controllers/featuregroupPreviewCtrl.js
- hopsworks-web/yo/app/views/featuregroupPreview.html
> [HOPSWORKS-1746] - append - Full screen feature group data preview

- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/CertificatesController.java
> [HOPSWORKS-1793] Increase certificate keysize

- hopsworks-IT/src/test/ruby/spec/helpers/epipe_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1768
> [HOPSWORKS-1768] Restrict the usage of scan operations

- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/airflow/AirflowDagFacade.java
> HOPSWORKS-1795 Close AirflowDagFacade connections

- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
> HOPSWORKS-1799 Fix fetching kubernetes_variable

- hopsworks-IT/src/test/ruby/spec/helpers/jupyter_helper.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/JupyterSettingsFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterJWTManager.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/JupyterSettings.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/views/jupyter/commonAdvancedConfig.html
- hopsworks-web/yo/app/views/jupyter/pythonConfig.html
> [HOPSWORKS-1314] It should be possible to start Jupyter with a Shared Dataset as base directory

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/erasureCode/ErasureCodeJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
> [HOPSWORKS-1818] Kakfa broker env variable not available in jobs

- hopsworks-IT/src/test/java/io/hops/hopsworks/WebDriverFactory.java
> [HOPSWORKS-1824] fix chrome driver

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeatureGroupPreviewResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-common/pom.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/OfflineFeatureGroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/online/OnlineFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-1672] Featurestore Descriptions containing ' cannot be handled by hive

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/NullJupyterNbVCSController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplate.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/jupyter/JupyterNotebookConfigTemplateBuilder.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/config/GitBackend.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jupyter/config/GitConfig.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/styles/form.css
- hopsworks-web/yo/app/views/jupyter/commonAdvancedConfig.html
- hopsworks-web/yo/app/views/jupyter/gitBackendAdvancedConfig.html
- hopsworks-web/yo/app/views/jupyterDashboard.html
- scripts/scp-deploy-frontend.sh
> HOPSWORKS-1839 jupyter gitlab

- hopsworks-IT/src/test/ruby/spec/helpers/prov_state_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/xattrs/XAttrsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/exceptions/MetadataException.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1791
> [HOPSWORKS-1791] [ePipe] Add support for large XAttrs

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-1782] Set C_INCLUDE_PATH and CPLUS_INCLUDE_PATH when installing libraries in Anaconda

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
> [HOPSWORKS-1838] Set NCCL_SOCKET_NTHREADS and NCCL_NSOCKS_PERTHREAD for distributed training

- hopsworks-IT/src/test/ruby/spec/maggy_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/maggy/MaggyService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/maggy/MaggyFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/maggy/MaggyDriver.java
(cherry picked from commit 6862a3d40ec7c8b036b0db74edef5278c61be99b)
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1634
> [HOPSWORKS-1634] MaggyFacade throws getSingleResult for findByAppId in parallel experiments

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/PKI.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/DistributedFsService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/security/BaseHadoopClientsService.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
Improvement
Load glassfish specific x.509 material and change the file format Hopsworks CA stores the signed certificates
It won't be able to load old host/superuser certificate
> [HOPSWORKS-1657] [HOPSWORKS-1657] System users x.509 v2

- hopsworks-IT/src/test/ruby/spec/helpers/elastic_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/epipe_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/prov_state_helper.rb
- hopsworks-IT/src/test/ruby/spec/prov_state_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1800
depends on HOPSWORKS-1786 to be merged first
> [HOPSWORKS-1800] cache provenance-epipe scan operations

- hopsworks-IT/src/test/ruby/spec/factories/xattr.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/search_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/xattr_helper.rb
- hopsworks-IT/src/test/ruby/spec/search_spec.rb
- hopsworks-IT/src/test/ruby/spec/xattrs_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/metadata/XAttrsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hdfs/xattrs/XAttrsController.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1834
https://github.com/logicalclocks/hops-testing-ee/pull/116
> [HOPSWORKS-1834] enable large xattr &fixes

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/featuregroup/Featuregroup.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDataset.java
cherry-picked from hopsworks-ee
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1892?atlOrigin=eyJpIjoiYzk5ZmY3ZmRhNzg4NGJlZTkxZDZhYjM4NGU3ZTg1ZjMiLCJwIjoiaiJ9
> [HOPSWORKS-1892] Training Dataset/feature group increment version on create

- hopsworks-IT/src/test/java/io/hops/hopsworks/RecoveryIT.java
- hopsworks-IT/src/test/ruby/spec/projects_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-web/yo/app/scripts/controllers/homeCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCreatorCtrl.js
- hopsworks-web/yo/app/scripts/controllers/projectCtrl.js
- hopsworks-web/yo/app/views/projectCreateModal.html
> [HOPSWORKS-1880] remove members from project creation

- hopsworks-IT/src/test/ruby/.env.example
- hopsworks-IT/src/test/ruby/spec/api_key_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/apiKey/ApiKeyResource.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/apiKey/ApiScope.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1896
New feature
Add functionality for Admin users to create API keys with Admin scope
No breaking changes
> [HOPSWORKS-1896] Create a privileged Admin API key scope visible only to Admins

- hopsworks-IT/src/test/ruby/spec/api_key_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/api_key_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AuthFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/apiKey/ApiKeyFilter.java
> [HOPSWORKS-1901] fix apikey filter

- README.md
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/DistributionStrategy.java
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/views/jupyter/jupyterConfigPanel.html
> [HOPSWORKS-1642] Upgrade to TensorFlow 2.2.0 and PyTorch 1.5.1

- hopsworks-IT/src/test/ruby/spec/maggy_spec.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1905
> [HOPSWORKS-1905] reset_session at the beginning of maggy_spec

- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1917?jql=text%20~%20%22notebooks%22
> [HOPSWORKS-1917] fixing the notebook names in the ruby tests

- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/HostsController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/client/HttpClient.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1919
bug fix
do not call consul in init
> [HOPSWORKS-1919] fix consul race condition

- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/FlinkProxyServlet.java
> HOPSWORKS-1908 Authenticate Flink proxy with API key

- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/ProjectsAdmin.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/project/ProjectService.java
Add API key required for ProjectService
Allow all HOPS_ADMIN users to createas project
Project createas change email to username
> HOPSWORKS-1899 Fixes for UsersAdminResource

- hopsworks-common/pom.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1922
Task
> [HOPSWORKS-1922] Bumpup service-discovery-clients version

- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AuthFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/kafka/KafkaResource.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/apiKey/ApiScope.java
- hopsworks-web/yo/app/scripts/controllers/profileCtrl.js
> [HOPSWORKS-1924] Add Kafka scope to API keys

- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/erasureCode/ErasureCodeJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/flink/FlinkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/yarn/YarnJob.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/sklearn/LocalhostSkLearnServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/tf/LocalhostTfServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/FlinkConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1805
> [HOPSWORKS-1805] consul for docker registry (#107)

- hopsworks-web/yo/app/views/projectSettings.html
> [HOPSWORKS-1935] Show project ID in the project settings

- hopsworks-admin/src/main/webapp/WEB-INF/beans.xml
- hopsworks-api/src/main/webapp/WEB-INF/beans.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/integrations/UnmanagedStereotype.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/AuthController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/PasswordRecovery.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UnmanagedPasswordRecovery.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UsersController.java
- hopsworks-common/src/main/resources/META-INF/beans.xml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1927
Task
> [HOPSWORKS-1927] Add an indirection layer to send password recovery notification to accomodate the Cloud mechanism

- hopsworks-IT/src/test/ruby/spec/prov_state_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ProjectProvenanceResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvLinksBeanParams.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/ops/ProvOpsBeanParams.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/provenance/state/ProvStateBeanParams.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/util/Pagination.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/PaginationParams.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvLinksBuilderIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvLinksBuilderImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvLinksParams.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsBuilderIface.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsBuilderImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/ProvOpsParams.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/dto/ProvLinksDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/ops/dto/ProvOpsDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/state/ProvStateBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/state/ProvStateParams.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1776
refactor
> [HOPSWORKS-1776] provenance fixes

- hopsworks-IT/src/test/ruby/spec/featurestore_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/split/TrainingDatasetSplit.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1929
> [HOPSWORKS-1929] Enforce unique names in training dataset splits

- hopsworks-api/src/main/java/com/predic8/membrane/servlet/embedded/MembraneServlet.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManagerImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/IoUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ProjectUtils.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1902
> [HOPSWORKS-1902] Changes to hopsworks community introduced by pr#147

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1954
> [HOPSWORKS-1954] Use hopsworks version as a tag for all docker images

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/RemoteAuth.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/ldap/ConfigureLdap.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/ldap/LdapConfigHelper.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/oauth/OAuthClientHelper.java
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/oauth/OAuthClientRegistration.java
- hopsworks-admin/src/main/webapp/WEB-INF/beans.xml
- hopsworks-admin/src/main/webapp/security/protected/admin/adminIndex.xhtml
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-api/src/main/webapp/WEB-INF/beans.xml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/remote/group/RemoteGroupProjectMappingFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/integrations/NullRemoteAuthStereotype.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/RemoteUsersDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/group/mapping/NullRemoteGroupMappingHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/group/mapping/RemoteGroupMappingHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/ldap/LdapHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/ldap/NullLdapHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/oauth/NullOAuthHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/oauth/OAuthHelper.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/oauth/OpenIdConstant.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/remote/oauth/OpenIdProviderConfig.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/remote/group/RemoteGroupProjectMapping.java
> #1-append fix for issue 1

- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/remote/user/oauth/OAuthClientRegistration.java
> #1-append-1 fix unused imoprt

- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/dataset_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dataset/util/DatasetPath.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1985
> [HOPSWORKS-1985] delete from shared dataset with full path fails

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-1806] Reduce LibraryInstaller logging

- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
> [HOPSWORKS-1835] spark umask

- hopsworks-IT/src/test/ruby/spec/helpers/conda_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/helpers/variables_helper.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_serving_spec.rb
- hopsworks-IT/src/test/ruby/spec/tf_inference_spec.rb
- hopsworks-IT/src/test/ruby/spec/tfserving_spec.rb
- hopsworks-admin/src/main/webapp/security/protected/admin/jupyterNotebooks.xhtml
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/LocalhostServingController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/serving/ServingStatusEnum.java
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
> [HOPSWORKS-2001] TFServing should use base image instead of the hops one

- pom.xml
> [HOPSWORKS-2007] Bump hops dependency to 3.2.0.0-RC1

- README.md
> [HOPSWORKS-2012] fix jenkins typo

- LICENSE_OF_DEPENDENCIES.md
- hopsworks-common/pom.xml
> [HOPSWORKS-1891] Remove unused commons-beanutils dependency

- hopsworks-IT/src/test/ruby/spec/ca_spec.rb
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/api/certificates/HostCertsResource.java
- hopsworks-ca/src/main/java/io/hops/hopsworks/ca/controllers/OpensslOperations.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/proxies/CAProxy.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2011
Task
REST endpoint to revoke all certificates based on a provided regex
No breaking changes
> [HOPSWORKS-2011] Revoke all certificates of a host

- hopsworks-web/yo/app/scripts/controllers/clusterUtilisationCtrl.js
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
> [HOPSWORKS-2020] Available GPUs not calculated correctly

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
> [HOPSWORKS-2006] - append - fix method name

- hopsworks-api/src/main/java/io/hops/hopsworks/api/airflow/AirflowDagDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/templates/airflow/AirflowOperator.java
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1504
> [HOPSWORKS-1504] Workflow builder should sanitize job names

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/execution/AbstractExecutionController.java
> [HOPSWORKS-1989] Edge case for Python jobs

- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobType.java
> [HOPSWORKS-1989][append] add Python job type

- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/tensorboard/TensorBoardProxyServlet.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/experiments/tensorboard/TensorBoardResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/tensorflow/config/TensorBoardProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/experiments/tensorboard/TensorBoardController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/tensorBoardCtrl.js
> [HOPSWORKS-2021] TensorBoard too slow loading many experiment runs and times out

- pom.xml
> [HOPSWORKS-2034] Bump hops to 3.2.0.0-RC2

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/serving_helper.rb
- hopsworks-IT/src/test/ruby/spec/sklearn_inference_spec.rb
> [HOPSWORKS-2000][append] sklearn_inference and execution_spec fixes

- pom.xml
> [HOPSWORKS-2039] Bump hops to 3.2.0.0-RC3

- hopsworks-IT/src/test/ruby/spec/execution_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/job_helper.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/JobDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jobs/executions/ExecutionsResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/jobs/configuration/JobConfiguration.java
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newTrainingDatasetCtrl.js
- hopsworks-web/yo/app/scripts/controllers/updateFeaturestoreStatisticModalCtrl.js
- hopsworks-web/yo/app/views/jobDetails.html
- hopsworks-web/yo/app/views/jobs.html
- hopsworks-web/yo/app/views/newJob.html
> [HOPSWORKS-1878] Add default args for Jobs

- hopsworks-web/yo/app/scripts/controllers/dataValidationCtrl.js
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
> [HOPSWORKS-1876] Data validation UI doesn't fill in Job parameters

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBeanParam.java
- hopsworks-web/yo/app/scripts/controllers/jobsCtrl.js
> [HOPSWORKS-2051] fix job page size

- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterProcessMgr.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2054
> [HOPSWORKS-2054] Increment Jupyter launch timeout

- hopsworks-web/yo/app/views/featurestore.html
- hopsworks-web/yo/app/views/jobs.html
> [HOPSWORKS-2015] fix featurestore tooltips

- hopsworks-web/yo/app/views/jupyter/pythonConfig.html
> [HOPSWORKS-2059] Base directory when starting Jupyter in python mode not set correctly

- pom.xml
> Bump hops to 3.2.0.0-RC4

- hopsworks-IT/pom.xml
- hopsworks-UT/pom.xml
- hopsworks-admin/pom.xml
- hopsworks-api/pom.xml
- hopsworks-ca/pom.xml
- hopsworks-cluster/pom.xml
- hopsworks-common/pom.xml
- hopsworks-dela/pom.xml
- hopsworks-ear/pom.xml
- hopsworks-jwt/pom.xml
- hopsworks-kmon/pom.xml
- hopsworks-persistence/pom.xml
- hopsworks-rest-utils/pom.xml
- hopsworks-testing/pom.xml
- hopsworks-web/pom.xml
- pom.xml
> Release version 1.4.1

- hopsworks-web/yo/app/scripts/controllers/featuregroupPreviewCtrl.js
- hopsworks-web/yo/app/views/featurestore.html
> [HOPSWORKS-2064] UI Fixes for data preview

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/FeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/hosts/ServiceDiscoveryController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/jdbc/FeaturestoreJdbcConnector.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
> [HOPSWORKS-1847] Online feature store storage connectors should not be stored in the database

- hopsworks-common/src/main/java/io/hops/hopsworks/common/elastic/ElasticClient.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/kafka/KafkaBrokers.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2068
> [HOPSWORKS-2068] Singleton init issues (ElasticClient, KafkaBrokers)

- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterController.java
Reverts logicalclocks/hopsworks#690
> Revert "[HOPSWORKS-1988] IPynb converter fails for notebooks which contain special characters …"

- hopsworks-IT/src/test/ruby/spec/featuregroup_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/FeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/provenance/core/HopsFSProvenanceController.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2067
> [HOPSWORKS-2067] shared featuregroup creation

- README.md
- hopsworks-api/src/main/java/io/hops/hopsworks/api/filter/AllowCORSFilter.java
- hopsworks-api/src/main/java/io/hops/hopsworks/rest/application/config/ApplicationConfig.java
> no cors filter

- hopsworks-web/yo/app/scripts/controllers/datasetsCtrl.js
> [HOPSWORKS-2061] fix dataset sort

- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2043][Append] Python 3.7 not set when re-creating environment

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
- hopsworks-web/yo/app/views/python.html
> [HOPSWORKS-2088] Users should be able to install a separate TensorFlow version than the default

- hopsworks-IT/src/test/ruby/spec/job_spec.rb
- hopsworks-IT/src/test/ruby/spec/jupyter_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/jupyter/JupyterService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/jupyter/config/JupyterConfigFilesGenerator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/spark/SparkYarnRunnerBuilder.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManager.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/JupyterManagerImpl.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/jupyter/LocalHostJupyterProcessMgr.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/ConfigurationUtil.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/SparkConfigurationUtil.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/jupyterCtrl.js
- hopsworks-web/yo/app/scripts/controllers/newJobCtrl.js
- hopsworks-web/yo/app/scripts/controllers/sparkConfigCtrl.js
- hopsworks-web/yo/app/views/jupyter/commonConfig.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1918
> [HOPSWORKS-1918] Spark executor memory not modifiable from UI when starting jupyter fix

- hopsworks-IT/pom.xml
- hopsworks-IT/src/test/java/io/hops/hopsworks/util/DBHelper.java
- hopsworks-IT/src/test/ruby/Gemfile
- hopsworks-IT/src/test/ruby/spec/admin_users_spec.rb
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- pom.xml
> [WIP] [HOPSWORKS-1387] Upgrade to NDB 8

- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/library/LibraryInstaller.java
> [HOPSWORKS-2098] Cannot remove libraries which failed to install

- README.md
> readme fix for integration tests

- hopsworks-web/yo/app/scripts/app.js
> [HOPSWORKS-2081] remove guardRegister for search

- hopsworks-web/yo/app/scripts/app.js
> [HOPSWORKS-2081] remove guardRegister from search

- hopsworks-web/yo/app/views/flinkConfig.html
> [HOPSWORKS-2025][append] fix typo

- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UserProfileDTO.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/user/UsersBuilder.java
- hopsworks-persistence/src/main/resources/META-INF/persistence.xml
> [HOPSWORKS-2112] add activated to user dto

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/commit/CommitResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/featuregroup/FeaturegroupService.java
> [HOPSWORKS-1374] Remove enterprise annotations

- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/environment/EnvironmentResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/python/library/LibraryResource.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/agent/AgentController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/dao/python/LibraryFacade.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/project/ProjectController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/python/environment/EnvironmentController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/python/PythonDep.java
> [HOPSWORKS-2109] Remove base_env from PythonDep

- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FeaturestoreService.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/storageconnector/FeaturestoreStorageConnectorService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/online/OnlineFeaturestoreController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/FeaturestoreStorageConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/storageconnectors/jdbc/FeaturestoreJdbcConnectorFacade.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/storageconnector/jdbc/FeaturestoreJdbcConnector.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/scripts/controllers/storageConnectorViewInfoCtrl.js
- hopsworks-web/yo/app/views/storageConnectorViewInfo.html
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1580
> [HOPSWORKS-1580] Online Feature Store JDBC password retrieval from UI

- hopsworks-IT/src/test/ruby/spec/helpers/hops_helper.rb
Restores the helper accidentally removed by HOPSWORKS-2025 
> Add hops_helper

- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupController.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/featuregroup/cached/CachedFeaturegroupDTO.java
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2122
> [HOPSWORKS-2122] Backend not handling null TimeTravelFormat sent by client

- hopsworks-IT/src/test/ruby/spec/helpers/featurestore_helper.rb
- hopsworks-IT/src/test/ruby/spec/trainingdataset_spec.rb
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/FsQueryBuilder.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/TrainingDatasetService.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/feature/TrainingDatasetFeatureDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/featurestore/trainingdatasets/TrainingDatasetController.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/featurestore/trainingdataset/TrainingDatasetFeature.java
- hopsworks-web/yo/app/views/trainingDatasetViewInfo.html
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2091
> [HOPSWORKS-2091] Label/Prediction feature metadata for training datasets

- hopsworks-web/yo/app/scripts/controllers/pythonCtrl.js
> [HOPSWORKS-1853][Append] After install users should be recommended to go to Ongoing Operations

- hopsworks-IT/src/test/ruby/spec/admin_users_spec.rb
- hopsworks-IT/src/test/ruby/spec/dataset_spec.rb
- hopsworks-IT/src/test/ruby/spec/helpers/admin_helper.rb
- hopsworks-admin/src/main/java/io/hops/hopsworks/admin/user/account/Register.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
- hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/dto/NewUserDTO.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UserValidator.java
- hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java
- hopsworks-persistence/src/main/java/io/hops/hopsworks/persistence/entity/user/security/apiKey/ApiScope.java
- hopsworks-rest-utils/src/main/java/io/hops/hopsworks/restutils/RESTCodes.java
- hopsworks-web/yo/app/views/userSettings.html
> [HOPSWORKS-2119] register user as admin
